domain_path: C:\Users\oussk\Downloads\ECG_anomaly_detection\hw_vitis\ecg_cnn\ecg_platform_\export\ecg_platform_\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
