@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 08 16:19:45 +0100 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim system_bd_wrapper_behav -key {Behavioral:sim_1:Functional:system_bd_wrapper} -tclbatch system_bd_wrapper.tcl -protoinst "protoinst_files/bd_e6ac.protoinst" -protoinst "protoinst_files/system_bd.protoinst" -log simulate.log"
call xsim  system_bd_wrapper_behav -key {Behavioral:sim_1:Functional:system_bd_wrapper} -tclbatch system_bd_wrapper.tcl -protoinst "protoinst_files/bd_e6ac.protoinst" -protoinst "protoinst_files/system_bd.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
