// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_exp_12_3_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [11:0] x;
output  [11:0] ap_return;
input   ap_ce;

reg[11:0] ap_return;

wire   [4:0] f_x_lsb_table_address0;
wire   [10:0] f_x_lsb_table_q0;
wire   [4:0] exp_x_msb_2_m_1_table_address0;
wire   [24:0] exp_x_msb_2_m_1_table_q0;
wire   [4:0] exp_x_msb_1_table_address0;
wire   [24:0] exp_x_msb_1_table_q0;
reg   [0:0] tmp_reg_417;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_417_pp0_iter1_reg;
reg   [3:0] tmp_9_reg_422;
reg   [3:0] tmp_9_reg_422_pp0_iter1_reg;
wire   [2:0] trunc_ln191_fu_161_p1;
reg   [2:0] trunc_ln191_reg_427;
reg   [2:0] trunc_ln191_reg_427_pp0_iter1_reg;
reg   [2:0] trunc_ln191_reg_427_pp0_iter2_reg;
reg   [10:0] f_x_lsb_reg_443;
reg   [10:0] f_x_lsb_reg_443_pp0_iter2_reg;
reg   [24:0] exp_x_msb_2_m_1_reg_449;
reg   [24:0] exp_x_msb_2_m_1_reg_449_pp0_iter2_reg;
reg   [18:0] tmp_s_reg_455;
wire   [24:0] exp_x_msb_2_lsb_m_1_fu_252_p2;
reg   [24:0] exp_x_msb_2_lsb_m_1_reg_465;
reg   [24:0] exp_x_msb_1_reg_470;
reg   [24:0] exp_x_msb_1_reg_470_pp0_iter4_reg;
reg   [24:0] y_lo_s_reg_476;
wire   [63:0] zext_ln204_fu_173_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln219_fu_178_p1;
wire   [63:0] zext_ln235_fu_220_p1;
reg    f_x_lsb_table_ce0_local;
reg    exp_x_msb_2_m_1_table_ce0_local;
reg    exp_x_msb_1_table_ce0_local;
wire   [24:0] y_lo_fu_129_p0;
wire   [24:0] y_lo_fu_129_p1;
wire   [4:0] x_lsb_ind_fu_165_p3;
wire   [4:0] x_msb_ind_2_fu_151_p4;
wire   [17:0] exp_x_lsb_m_1_fu_189_p4;
wire   [24:0] f_x_msb_2_lsb_fu_204_p0;
wire   [17:0] f_x_msb_2_lsb_fu_204_p1;
wire   [42:0] f_x_msb_2_lsb_fu_204_p2;
wire   [4:0] x_msb_ind_1_fu_183_p3;
wire   [18:0] shl_ln_fu_228_p5;
wire   [19:0] zext_ln223_1_fu_238_p1;
wire   [19:0] zext_ln223_fu_225_p1;
wire   [19:0] add_ln223_fu_242_p2;
wire   [24:0] zext_ln223_2_fu_248_p1;
wire   [49:0] y_lo_fu_129_p2;
wire   [24:0] y_l_fu_275_p2;
wire   [0:0] tmp_3_fu_287_p3;
wire   [0:0] overf_fu_279_p3;
wire   [0:0] tmp_4_fu_295_p3;
wire   [0:0] tmp_5_fu_303_p3;
wire   [0:0] or_ln245_1_fu_357_p2;
wire   [0:0] or_ln245_fu_351_p2;
wire   [0:0] tmp_6_fu_311_p3;
wire   [0:0] tmp_7_fu_319_p3;
wire   [0:0] tmp_10_fu_335_p3;
wire   [0:0] tmp_11_fu_343_p3;
wire   [0:0] or_ln245_4_fu_375_p2;
wire   [0:0] tmp_8_fu_327_p3;
wire   [0:0] or_ln245_5_fu_381_p2;
wire   [0:0] or_ln245_3_fu_369_p2;
wire   [0:0] or_ln245_6_fu_387_p2;
wire   [0:0] or_ln245_2_fu_363_p2;
wire   [0:0] overf_1_fu_393_p2;
wire   [11:0] trunc_ln_fu_399_p4;
wire   [11:0] select_ln259_fu_409_p3;
reg    ap_ce_reg;
reg   [11:0] x_int_reg;
reg   [11:0] ap_return_int_reg;
wire   [42:0] f_x_msb_2_lsb_fu_204_p00;
wire   [42:0] f_x_msb_2_lsb_fu_204_p10;
wire   [49:0] y_lo_fu_129_p00;
wire   [49:0] y_lo_fu_129_p10;

ecg_cnn_exp_12_3_s_f_x_lsb_table_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
f_x_lsb_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(f_x_lsb_table_address0),
    .ce0(f_x_lsb_table_ce0_local),
    .q0(f_x_lsb_table_q0)
);

ecg_cnn_exp_12_3_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R #(
    .DataWidth( 25 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
exp_x_msb_2_m_1_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_x_msb_2_m_1_table_address0),
    .ce0(exp_x_msb_2_m_1_table_ce0_local),
    .q0(exp_x_msb_2_m_1_table_q0)
);

ecg_cnn_exp_12_3_s_exp_x_msb_1_table_ROM_AUTO_1R #(
    .DataWidth( 25 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
exp_x_msb_1_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_x_msb_1_table_address0),
    .ce0(exp_x_msb_1_table_ce0_local),
    .q0(exp_x_msb_1_table_q0)
);

ecg_cnn_mul_25ns_25ns_50_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 50 ))
mul_25ns_25ns_50_1_0_U285(
    .din0(y_lo_fu_129_p0),
    .din1(y_lo_fu_129_p1),
    .dout(y_lo_fu_129_p2)
);

ecg_cnn_mul_25ns_18ns_43_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 43 ))
mul_25ns_18ns_43_1_0_U286(
    .din0(f_x_msb_2_lsb_fu_204_p0),
    .din1(f_x_msb_2_lsb_fu_204_p1),
    .dout(f_x_msb_2_lsb_fu_204_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln259_fu_409_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_x_msb_1_reg_470 <= exp_x_msb_1_table_q0;
        exp_x_msb_1_reg_470_pp0_iter4_reg <= exp_x_msb_1_reg_470;
        exp_x_msb_2_lsb_m_1_reg_465 <= exp_x_msb_2_lsb_m_1_fu_252_p2;
        exp_x_msb_2_m_1_reg_449 <= exp_x_msb_2_m_1_table_q0;
        exp_x_msb_2_m_1_reg_449_pp0_iter2_reg <= exp_x_msb_2_m_1_reg_449;
        f_x_lsb_reg_443 <= f_x_lsb_table_q0;
        f_x_lsb_reg_443_pp0_iter2_reg <= f_x_lsb_reg_443;
        tmp_9_reg_422 <= {{x_int_reg[11:8]}};
        tmp_9_reg_422_pp0_iter1_reg <= tmp_9_reg_422;
        tmp_reg_417 <= x_int_reg[32'd11];
        tmp_reg_417_pp0_iter1_reg <= tmp_reg_417;
        tmp_s_reg_455 <= {{f_x_msb_2_lsb_fu_204_p2[42:24]}};
        trunc_ln191_reg_427 <= trunc_ln191_fu_161_p1;
        trunc_ln191_reg_427_pp0_iter1_reg <= trunc_ln191_reg_427;
        trunc_ln191_reg_427_pp0_iter2_reg <= trunc_ln191_reg_427_pp0_iter1_reg;
        y_lo_s_reg_476 <= {{y_lo_fu_129_p2[49:25]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln259_fu_409_p3;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_x_msb_1_table_ce0_local = 1'b1;
    end else begin
        exp_x_msb_1_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        exp_x_msb_2_m_1_table_ce0_local = 1'b1;
    end else begin
        exp_x_msb_2_m_1_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        f_x_lsb_table_ce0_local = 1'b1;
    end else begin
        f_x_lsb_table_ce0_local = 1'b0;
    end
end

assign add_ln223_fu_242_p2 = (zext_ln223_1_fu_238_p1 + zext_ln223_fu_225_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign exp_x_lsb_m_1_fu_189_p4 = {{{trunc_ln191_reg_427_pp0_iter1_reg}, {4'd0}}, {f_x_lsb_reg_443}};

assign exp_x_msb_1_table_address0 = zext_ln235_fu_220_p1;

assign exp_x_msb_2_lsb_m_1_fu_252_p2 = (exp_x_msb_2_m_1_reg_449_pp0_iter2_reg + zext_ln223_2_fu_248_p1);

assign exp_x_msb_2_m_1_table_address0 = zext_ln219_fu_178_p1;

assign f_x_lsb_table_address0 = zext_ln204_fu_173_p1;

assign f_x_msb_2_lsb_fu_204_p0 = f_x_msb_2_lsb_fu_204_p00;

assign f_x_msb_2_lsb_fu_204_p00 = exp_x_msb_2_m_1_reg_449;

assign f_x_msb_2_lsb_fu_204_p1 = f_x_msb_2_lsb_fu_204_p10;

assign f_x_msb_2_lsb_fu_204_p10 = exp_x_lsb_m_1_fu_189_p4;

assign or_ln245_1_fu_357_p2 = (tmp_5_fu_303_p3 | tmp_4_fu_295_p3);

assign or_ln245_2_fu_363_p2 = (or_ln245_fu_351_p2 | or_ln245_1_fu_357_p2);

assign or_ln245_3_fu_369_p2 = (tmp_7_fu_319_p3 | tmp_6_fu_311_p3);

assign or_ln245_4_fu_375_p2 = (tmp_11_fu_343_p3 | tmp_10_fu_335_p3);

assign or_ln245_5_fu_381_p2 = (tmp_8_fu_327_p3 | or_ln245_4_fu_375_p2);

assign or_ln245_6_fu_387_p2 = (or_ln245_5_fu_381_p2 | or_ln245_3_fu_369_p2);

assign or_ln245_fu_351_p2 = (tmp_3_fu_287_p3 | overf_fu_279_p3);

assign overf_1_fu_393_p2 = (or_ln245_6_fu_387_p2 | or_ln245_2_fu_363_p2);

assign overf_fu_279_p3 = y_l_fu_275_p2[32'd24];

assign select_ln259_fu_409_p3 = ((overf_1_fu_393_p2[0:0] == 1'b1) ? 12'd2047 : trunc_ln_fu_399_p4);

assign shl_ln_fu_228_p5 = {{{{trunc_ln191_reg_427_pp0_iter2_reg}, {4'd0}}, {f_x_lsb_reg_443_pp0_iter2_reg}}, {1'd0}};

assign tmp_10_fu_335_p3 = y_l_fu_275_p2[32'd17];

assign tmp_11_fu_343_p3 = y_l_fu_275_p2[32'd16];

assign tmp_3_fu_287_p3 = y_l_fu_275_p2[32'd23];

assign tmp_4_fu_295_p3 = y_l_fu_275_p2[32'd22];

assign tmp_5_fu_303_p3 = y_l_fu_275_p2[32'd21];

assign tmp_6_fu_311_p3 = y_l_fu_275_p2[32'd20];

assign tmp_7_fu_319_p3 = y_l_fu_275_p2[32'd19];

assign tmp_8_fu_327_p3 = y_l_fu_275_p2[32'd18];

assign trunc_ln191_fu_161_p1 = x_int_reg[2:0];

assign trunc_ln_fu_399_p4 = {{y_l_fu_275_p2[16:5]}};

assign x_lsb_ind_fu_165_p3 = {{trunc_ln191_fu_161_p1}, {2'd0}};

assign x_msb_ind_1_fu_183_p3 = {{tmp_reg_417_pp0_iter1_reg}, {tmp_9_reg_422_pp0_iter1_reg}};

assign x_msb_ind_2_fu_151_p4 = {{x_int_reg[7:3]}};

assign y_l_fu_275_p2 = (exp_x_msb_1_reg_470_pp0_iter4_reg + y_lo_s_reg_476);

assign y_lo_fu_129_p0 = y_lo_fu_129_p00;

assign y_lo_fu_129_p00 = exp_x_msb_2_lsb_m_1_reg_465;

assign y_lo_fu_129_p1 = y_lo_fu_129_p10;

assign y_lo_fu_129_p10 = exp_x_msb_1_reg_470;

assign zext_ln204_fu_173_p1 = x_lsb_ind_fu_165_p3;

assign zext_ln219_fu_178_p1 = x_msb_ind_2_fu_151_p4;

assign zext_ln223_1_fu_238_p1 = shl_ln_fu_228_p5;

assign zext_ln223_2_fu_248_p1 = add_ln223_fu_242_p2;

assign zext_ln223_fu_225_p1 = tmp_s_reg_455;

assign zext_ln235_fu_220_p1 = x_msb_ind_1_fu_183_p3;

endmodule //ecg_cnn_exp_12_3_s
