-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_146_2_w_local_82_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_146_2_w_local_82_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000010011000", 1 => "111101100111", 2 => "111110001100", 3 => "111110000111", 
    4 => "110110111001", 5 => "110100000001", 6 => "110110010100", 7 => "111101101011", 
    8 => "010011011110", 9 => "111101110100", 10 => "000001100110", 11 => "000010100001", 
    12 => "111010111000", 13 => "000000000111", 14 => "000011001001", 15 => "111010110110", 
    16 => "001101111110", 17 => "000001001100", 18 => "000001111000", 19 => "000000001100", 
    20 => "111111001110", 21 => "111111101000", 22 => "000010011001", 23 => "111101001000", 
    24 => "111001011111", 25 => "000001111000", 26 => "000011011011", 27 => "111010000000", 
    28 => "111111011001", 29 => "111101011010", 30 => "000010101000", 31 => "000010001100", 
    32 => "001111110010", 33 => "111111001100", 34 => "000000001010", 35 => "000000101100", 
    36 => "111101011011", 37 => "111100101010", 38 => "111110000110", 39 => "111111110000", 
    40 => "010101001101", 41 => "111110100111", 42 => "000011000011", 43 => "111110110110", 
    44 => "001111100100", 45 => "000000111100", 46 => "000000000000", 47 => "000001100101", 
    48 => "111101100110", 49 => "111111101000", 50 => "111101101010", 51 => "111100100110", 
    52 => "010010000110", 53 => "111111010010", 54 => "000010001001", 55 => "000001000000", 
    56 => "111100010001", 57 => "000001110100", 58 => "000001011000", 59 => "111101010111", 
    60 => "111010110010", 61 => "000010011101", 62 => "000000101000", 63 => "111111011111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

