-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_dense_relu is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (11 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (11 downto 0);
    output_0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_0_ap_vld : OUT STD_LOGIC;
    output_1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_ap_vld : OUT STD_LOGIC;
    output_2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_2_ap_vld : OUT STD_LOGIC;
    output_3 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_3_ap_vld : OUT STD_LOGIC;
    output_4 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_4_ap_vld : OUT STD_LOGIC;
    output_5 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_5_ap_vld : OUT STD_LOGIC;
    output_6 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_6_ap_vld : OUT STD_LOGIC;
    output_7 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_7_ap_vld : OUT STD_LOGIC;
    output_8 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_8_ap_vld : OUT STD_LOGIC;
    output_9 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_9_ap_vld : OUT STD_LOGIC;
    output_10 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_10_ap_vld : OUT STD_LOGIC;
    output_11 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_11_ap_vld : OUT STD_LOGIC;
    output_12 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_12_ap_vld : OUT STD_LOGIC;
    output_13 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_13_ap_vld : OUT STD_LOGIC;
    output_14 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_14_ap_vld : OUT STD_LOGIC;
    output_15 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_15_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_dense_relu is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_36 : STD_LOGIC_VECTOR (7 downto 0) := "00110110";
    constant ap_const_lv8_E6 : STD_LOGIC_VECTOR (7 downto 0) := "11100110";
    constant ap_const_lv8_52 : STD_LOGIC_VECTOR (7 downto 0) := "01010010";
    constant ap_const_lv8_F4 : STD_LOGIC_VECTOR (7 downto 0) := "11110100";
    constant ap_const_lv8_F6 : STD_LOGIC_VECTOR (7 downto 0) := "11110110";
    constant ap_const_lv8_EC : STD_LOGIC_VECTOR (7 downto 0) := "11101100";
    constant ap_const_lv8_51 : STD_LOGIC_VECTOR (7 downto 0) := "01010001";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv8_57 : STD_LOGIC_VECTOR (7 downto 0) := "01010111";
    constant ap_const_lv8_4A : STD_LOGIC_VECTOR (7 downto 0) := "01001010";
    constant ap_const_lv8_26 : STD_LOGIC_VECTOR (7 downto 0) := "00100110";
    constant ap_const_lv8_D8 : STD_LOGIC_VECTOR (7 downto 0) := "11011000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln144_fu_425_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln144_reg_679 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln144_fu_431_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln144_reg_684 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p35 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_reg_690 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start : STD_LOGIC;
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done : STD_LOGIC;
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_idle : STD_LOGIC;
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_ready : STD_LOGIC;
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out_ap_vld : STD_LOGIC;
    signal grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln144_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal u_fu_164 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal select_ln150_fu_522_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal acc_fu_436_p33 : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_fu_436_p34 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln150_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln146_fu_512_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal acc_fu_436_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal acc_fu_436_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_146_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln145 : IN STD_LOGIC_VECTOR (7 downto 0);
        u : IN STD_LOGIC_VECTOR (3 downto 0);
        input_0_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_1_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_3_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_4_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_5_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_6_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_7_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_8_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_9_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_10_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_11_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_12_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_13_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_14_val : IN STD_LOGIC_VECTOR (11 downto 0);
        input_15_val : IN STD_LOGIC_VECTOR (11 downto 0);
        phi_ln148_out : OUT STD_LOGIC_VECTOR (11 downto 0);
        phi_ln148_out_ap_vld : OUT STD_LOGIC );
    end component;


    component ecg_cnn_sparsemux_33_4_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380 : component ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_146_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start,
        ap_done => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done,
        ap_idle => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_idle,
        ap_ready => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_ready,
        sext_ln145 => acc_reg_690,
        u => trunc_ln144_reg_684,
        input_0_val => input_0_val,
        input_1_val => input_1_val,
        input_2_val => input_2_val,
        input_3_val => input_3_val,
        input_4_val => input_4_val,
        input_5_val => input_5_val,
        input_6_val => input_6_val,
        input_7_val => input_7_val,
        input_8_val => input_8_val,
        input_9_val => input_9_val,
        input_10_val => input_10_val,
        input_11_val => input_11_val,
        input_12_val => input_12_val,
        input_13_val => input_13_val,
        input_14_val => input_14_val,
        input_15_val => input_15_val,
        phi_ln148_out => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out,
        phi_ln148_out_ap_vld => grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out_ap_vld);

    sparsemux_33_4_8_1_1_U230 : component ecg_cnn_sparsemux_33_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        CASE11 => "1011",
        din11_WIDTH => 8,
        CASE12 => "1100",
        din12_WIDTH => 8,
        CASE13 => "1101",
        din13_WIDTH => 8,
        CASE14 => "1110",
        din14_WIDTH => 8,
        CASE15 => "1111",
        din15_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_0,
        din1 => ap_const_lv8_6B,
        din2 => ap_const_lv8_36,
        din3 => ap_const_lv8_E6,
        din4 => ap_const_lv8_52,
        din5 => ap_const_lv8_F4,
        din6 => ap_const_lv8_F6,
        din7 => ap_const_lv8_EC,
        din8 => ap_const_lv8_51,
        din9 => ap_const_lv8_8,
        din10 => ap_const_lv8_57,
        din11 => ap_const_lv8_4A,
        din12 => ap_const_lv8_EC,
        din13 => ap_const_lv8_51,
        din14 => ap_const_lv8_26,
        din15 => ap_const_lv8_D8,
        def => acc_fu_436_p33,
        sel => acc_fu_436_p34,
        dout => acc_fu_436_p35);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln144_fu_419_p2 = ap_const_lv1_0))) then 
                    grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_ready = ap_const_logic_1)) then 
                    grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    u_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                u_fu_164 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                u_fu_164 <= add_ln144_reg_679;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                acc_reg_690 <= acc_fu_436_p35;
                add_ln144_reg_679 <= add_ln144_fu_425_p2;
                trunc_ln144_reg_684 <= trunc_ln144_fu_431_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done, icmp_ln144_fu_419_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln144_fu_419_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    acc_fu_436_p33 <= "XXXXXXXX";
    acc_fu_436_p34 <= u_fu_164(4 - 1 downto 0);
    add_ln144_fu_425_p2 <= std_logic_vector(unsigned(u_fu_164) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done)
    begin
        if ((grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln144_fu_419_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln144_fu_419_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln144_fu_419_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln144_fu_419_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start <= grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_ap_start_reg;
    icmp_ln144_fu_419_p2 <= "1" when (u_fu_164 = ap_const_lv5_10) else "0";
    icmp_ln150_fu_516_p2 <= "1" when (signed(grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out) > signed(ap_const_lv12_0)) else "0";
    output_0 <= select_ln150_fu_522_p3;

    output_0_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_0))) then 
            output_0_ap_vld <= ap_const_logic_1;
        else 
            output_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_1 <= select_ln150_fu_522_p3;
    output_10 <= select_ln150_fu_522_p3;

    output_10_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_A))) then 
            output_10_ap_vld <= ap_const_logic_1;
        else 
            output_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_11 <= select_ln150_fu_522_p3;

    output_11_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_B))) then 
            output_11_ap_vld <= ap_const_logic_1;
        else 
            output_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_12 <= select_ln150_fu_522_p3;

    output_12_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_C))) then 
            output_12_ap_vld <= ap_const_logic_1;
        else 
            output_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_13 <= select_ln150_fu_522_p3;

    output_13_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_D))) then 
            output_13_ap_vld <= ap_const_logic_1;
        else 
            output_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_14 <= select_ln150_fu_522_p3;

    output_14_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_E))) then 
            output_14_ap_vld <= ap_const_logic_1;
        else 
            output_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_15 <= select_ln150_fu_522_p3;

    output_15_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_F))) then 
            output_15_ap_vld <= ap_const_logic_1;
        else 
            output_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    output_1_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_1))) then 
            output_1_ap_vld <= ap_const_logic_1;
        else 
            output_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_2 <= select_ln150_fu_522_p3;

    output_2_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_2))) then 
            output_2_ap_vld <= ap_const_logic_1;
        else 
            output_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_3 <= select_ln150_fu_522_p3;

    output_3_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_3))) then 
            output_3_ap_vld <= ap_const_logic_1;
        else 
            output_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_4 <= select_ln150_fu_522_p3;

    output_4_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_4))) then 
            output_4_ap_vld <= ap_const_logic_1;
        else 
            output_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_5 <= select_ln150_fu_522_p3;

    output_5_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_5))) then 
            output_5_ap_vld <= ap_const_logic_1;
        else 
            output_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_6 <= select_ln150_fu_522_p3;

    output_6_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_6))) then 
            output_6_ap_vld <= ap_const_logic_1;
        else 
            output_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_7 <= select_ln150_fu_522_p3;

    output_7_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_7))) then 
            output_7_ap_vld <= ap_const_logic_1;
        else 
            output_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_8 <= select_ln150_fu_522_p3;

    output_8_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_8))) then 
            output_8_ap_vld <= ap_const_logic_1;
        else 
            output_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_9 <= select_ln150_fu_522_p3;

    output_9_ap_vld_assign_proc : process(trunc_ln144_reg_684, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (trunc_ln144_reg_684 = ap_const_lv4_9))) then 
            output_9_ap_vld <= ap_const_logic_1;
        else 
            output_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln150_fu_522_p3 <= 
        trunc_ln146_fu_512_p1 when (icmp_ln150_fu_516_p2(0) = '1') else 
        ap_const_lv11_0;
    trunc_ln144_fu_431_p1 <= u_fu_164(4 - 1 downto 0);
    trunc_ln146_fu_512_p1 <= grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380_phi_ln148_out(11 - 1 downto 0);
end behav;
