-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_maxpool is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_0_ce0 : OUT STD_LOGIC;
    input_0_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_0_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_0_ce1 : OUT STD_LOGIC;
    input_0_q1 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_1_ce0 : OUT STD_LOGIC;
    input_1_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_1_ce1 : OUT STD_LOGIC;
    input_1_q1 : IN STD_LOGIC_VECTOR (10 downto 0);
    output_0_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_0_ce0 : OUT STD_LOGIC;
    output_0_0_we0 : OUT STD_LOGIC;
    output_0_0_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_0_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_1_ce0 : OUT STD_LOGIC;
    output_0_1_we0 : OUT STD_LOGIC;
    output_0_1_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_0_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_2_ce0 : OUT STD_LOGIC;
    output_0_2_we0 : OUT STD_LOGIC;
    output_0_2_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_0_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_3_ce0 : OUT STD_LOGIC;
    output_0_3_we0 : OUT STD_LOGIC;
    output_0_3_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_0_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_0_4_ce0 : OUT STD_LOGIC;
    output_0_4_we0 : OUT STD_LOGIC;
    output_0_4_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_0_ce0 : OUT STD_LOGIC;
    output_1_0_we0 : OUT STD_LOGIC;
    output_1_0_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_1_ce0 : OUT STD_LOGIC;
    output_1_1_we0 : OUT STD_LOGIC;
    output_1_1_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_2_ce0 : OUT STD_LOGIC;
    output_1_2_we0 : OUT STD_LOGIC;
    output_1_2_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_3_ce0 : OUT STD_LOGIC;
    output_1_3_we0 : OUT STD_LOGIC;
    output_1_3_d0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    output_1_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    output_1_4_ce0 : OUT STD_LOGIC;
    output_1_4_we0 : OUT STD_LOGIC;
    output_1_4_d0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of ecg_cnn_maxpool is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv12_B28 : STD_LOGIC_VECTOR (11 downto 0) := "101100101000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv9_165 : STD_LOGIC_VECTOR (8 downto 0) := "101100101";
    constant ap_const_lv9_5 : STD_LOGIC_VECTOR (8 downto 0) := "000000101";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv19_334 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001100110100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln55_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln56_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln56_reg_530_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln55_fu_343_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter10_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln55_reg_535_pp0_iter11_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln55_fu_384_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_reg_543_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_fu_388_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_reg_549 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_reg_549_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_cast_reg_554 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_cast_reg_554_pp0_iter13_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln56_fu_452_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln56_reg_579 : STD_LOGIC_VECTOR (2 downto 0);
    signal maxval_2_fu_477_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal maxval_2_reg_583 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_fu_426_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln61_fu_441_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln64_fu_491_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_96 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln56_fu_357_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal f_fu_100 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln55_1_fu_377_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_104 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln55_1_fu_323_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (11 downto 0);
    signal input_0_ce1_local : STD_LOGIC;
    signal input_0_ce0_local : STD_LOGIC;
    signal input_1_ce1_local : STD_LOGIC;
    signal input_1_ce0_local : STD_LOGIC;
    signal output_0_3_we0_local : STD_LOGIC;
    signal output_0_3_ce0_local : STD_LOGIC;
    signal output_0_2_we0_local : STD_LOGIC;
    signal output_0_2_ce0_local : STD_LOGIC;
    signal output_0_1_we0_local : STD_LOGIC;
    signal output_0_1_ce0_local : STD_LOGIC;
    signal output_0_0_we0_local : STD_LOGIC;
    signal output_0_0_ce0_local : STD_LOGIC;
    signal output_0_4_we0_local : STD_LOGIC;
    signal output_0_4_ce0_local : STD_LOGIC;
    signal output_1_3_we0_local : STD_LOGIC;
    signal output_1_3_ce0_local : STD_LOGIC;
    signal output_1_2_we0_local : STD_LOGIC;
    signal output_1_2_ce0_local : STD_LOGIC;
    signal output_1_1_we0_local : STD_LOGIC;
    signal output_1_1_ce0_local : STD_LOGIC;
    signal output_1_0_we0_local : STD_LOGIC;
    signal output_1_0_ce0_local : STD_LOGIC;
    signal output_1_4_we0_local : STD_LOGIC;
    signal output_1_4_ce0_local : STD_LOGIC;
    signal grp_fu_351_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln55_fu_371_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln56_fu_401_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln56_fu_401_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln56_fu_401_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_2_fu_417_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_fu_432_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_351_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal v_fu_464_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal maxval_fu_457_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln62_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_485_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln56_fu_401_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_urem_9ns_4ns_3_13_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component ecg_cnn_mul_9ns_11ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component ecg_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_9ns_4ns_3_13_1_U25 : component ecg_cnn_urem_9ns_4ns_3_13_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 4,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln55_fu_343_p3,
        din1 => grp_fu_351_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_351_p2);

    mul_9ns_11ns_19_1_1_U26 : component ecg_cnn_mul_9ns_11ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln56_fu_401_p0,
        din1 => mul_ln56_fu_401_p1,
        dout => mul_ln56_fu_401_p2);

    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    f_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    f_fu_100 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter12 = ap_const_logic_1)) then 
                    f_fu_100 <= select_ln55_1_fu_377_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_96 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_96 <= add_ln56_fu_357_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln55_fu_317_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_104 <= add_ln55_1_fu_323_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_104 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln56_reg_530_pp0_iter10_reg <= icmp_ln56_reg_530_pp0_iter9_reg;
                icmp_ln56_reg_530_pp0_iter11_reg <= icmp_ln56_reg_530_pp0_iter10_reg;
                icmp_ln56_reg_530_pp0_iter2_reg <= icmp_ln56_reg_530;
                icmp_ln56_reg_530_pp0_iter3_reg <= icmp_ln56_reg_530_pp0_iter2_reg;
                icmp_ln56_reg_530_pp0_iter4_reg <= icmp_ln56_reg_530_pp0_iter3_reg;
                icmp_ln56_reg_530_pp0_iter5_reg <= icmp_ln56_reg_530_pp0_iter4_reg;
                icmp_ln56_reg_530_pp0_iter6_reg <= icmp_ln56_reg_530_pp0_iter5_reg;
                icmp_ln56_reg_530_pp0_iter7_reg <= icmp_ln56_reg_530_pp0_iter6_reg;
                icmp_ln56_reg_530_pp0_iter8_reg <= icmp_ln56_reg_530_pp0_iter7_reg;
                icmp_ln56_reg_530_pp0_iter9_reg <= icmp_ln56_reg_530_pp0_iter8_reg;
                lshr_ln_reg_549 <= select_ln55_1_fu_377_p3(2 downto 1);
                lshr_ln_reg_549_pp0_iter13_reg <= lshr_ln_reg_549;
                maxval_2_reg_583 <= maxval_2_fu_477_p3;
                select_ln55_reg_535_pp0_iter10_reg <= select_ln55_reg_535_pp0_iter9_reg;
                select_ln55_reg_535_pp0_iter11_reg <= select_ln55_reg_535_pp0_iter10_reg;
                select_ln55_reg_535_pp0_iter2_reg <= select_ln55_reg_535;
                select_ln55_reg_535_pp0_iter3_reg <= select_ln55_reg_535_pp0_iter2_reg;
                select_ln55_reg_535_pp0_iter4_reg <= select_ln55_reg_535_pp0_iter3_reg;
                select_ln55_reg_535_pp0_iter5_reg <= select_ln55_reg_535_pp0_iter4_reg;
                select_ln55_reg_535_pp0_iter6_reg <= select_ln55_reg_535_pp0_iter5_reg;
                select_ln55_reg_535_pp0_iter7_reg <= select_ln55_reg_535_pp0_iter6_reg;
                select_ln55_reg_535_pp0_iter8_reg <= select_ln55_reg_535_pp0_iter7_reg;
                select_ln55_reg_535_pp0_iter9_reg <= select_ln55_reg_535_pp0_iter8_reg;
                tmp_cast_reg_554 <= mul_ln56_fu_401_p2(18 downto 12);
                tmp_cast_reg_554_pp0_iter13_reg <= tmp_cast_reg_554;
                trunc_ln55_reg_543 <= trunc_ln55_fu_384_p1;
                trunc_ln55_reg_543_pp0_iter13_reg <= trunc_ln55_reg_543;
                trunc_ln56_reg_579 <= trunc_ln56_fu_452_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln56_reg_530 <= icmp_ln56_fu_337_p2;
                select_ln55_reg_535 <= select_ln55_fu_343_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln55_1_fu_323_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv12_1));
    add_ln55_fu_371_p2 <= std_logic_vector(unsigned(f_fu_100) + unsigned(ap_const_lv4_1));
    add_ln56_fu_357_p2 <= std_logic_vector(unsigned(select_ln55_fu_343_p3) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln55_fu_317_p2)
    begin
        if (((icmp_ln55_fu_317_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_104;
        end if; 
    end process;

    grp_fu_351_p1 <= ap_const_lv9_5(4 - 1 downto 0);
    icmp_ln55_fu_317_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv12_B28) else "0";
    icmp_ln56_fu_337_p2 <= "1" when (i_fu_96 = ap_const_lv9_165) else "0";
    icmp_ln62_fu_471_p2 <= "1" when (unsigned(v_fu_464_p3) > unsigned(maxval_fu_457_p3)) else "0";
    input_0_address0 <= zext_ln61_fu_441_p1(12 - 1 downto 0);
    input_0_address1 <= zext_ln58_fu_426_p1(12 - 1 downto 0);
    input_0_ce0 <= input_0_ce0_local;

    input_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            input_0_ce0_local <= ap_const_logic_1;
        else 
            input_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_0_ce1 <= input_0_ce1_local;

    input_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            input_0_ce1_local <= ap_const_logic_1;
        else 
            input_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    input_1_address0 <= zext_ln61_fu_441_p1(12 - 1 downto 0);
    input_1_address1 <= zext_ln58_fu_426_p1(12 - 1 downto 0);
    input_1_ce0 <= input_1_ce0_local;

    input_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            input_1_ce0_local <= ap_const_logic_1;
        else 
            input_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_1_ce1 <= input_1_ce1_local;

    input_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            input_1_ce1_local <= ap_const_logic_1;
        else 
            input_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_388_p4 <= select_ln55_1_fu_377_p3(2 downto 1);
    maxval_2_fu_477_p3 <= 
        v_fu_464_p3 when (icmp_ln62_fu_471_p2(0) = '1') else 
        maxval_fu_457_p3;
    maxval_fu_457_p3 <= 
        input_1_q1 when (trunc_ln55_reg_543(0) = '1') else 
        input_0_q1;
    mul_ln56_fu_401_p0 <= mul_ln56_fu_401_p00(9 - 1 downto 0);
    mul_ln56_fu_401_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln55_reg_535_pp0_iter11_reg),19));
    mul_ln56_fu_401_p1 <= ap_const_lv19_334(11 - 1 downto 0);
    output_0_0_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_0_0_ce0 <= output_0_0_ce0_local;

    output_0_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_0_0_ce0_local <= ap_const_logic_1;
        else 
            output_0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_0_d0 <= maxval_2_reg_583;
    output_0_0_we0 <= output_0_0_we0_local;

    output_0_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_0) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_0))) then 
            output_0_0_we0_local <= ap_const_logic_1;
        else 
            output_0_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_1_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_0_1_ce0 <= output_0_1_ce0_local;

    output_0_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_0_1_ce0_local <= ap_const_logic_1;
        else 
            output_0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_1_d0 <= maxval_2_reg_583;
    output_0_1_we0 <= output_0_1_we0_local;

    output_0_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_1) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_0))) then 
            output_0_1_we0_local <= ap_const_logic_1;
        else 
            output_0_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_2_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_0_2_ce0 <= output_0_2_ce0_local;

    output_0_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_0_2_ce0_local <= ap_const_logic_1;
        else 
            output_0_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_2_d0 <= maxval_2_reg_583;
    output_0_2_we0 <= output_0_2_we0_local;

    output_0_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_2) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_0))) then 
            output_0_2_we0_local <= ap_const_logic_1;
        else 
            output_0_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_3_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_0_3_ce0 <= output_0_3_ce0_local;

    output_0_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_0_3_ce0_local <= ap_const_logic_1;
        else 
            output_0_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_3_d0 <= maxval_2_reg_583;
    output_0_3_we0 <= output_0_3_we0_local;

    output_0_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_3) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_0))) then 
            output_0_3_we0_local <= ap_const_logic_1;
        else 
            output_0_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_4_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_0_4_ce0 <= output_0_4_ce0_local;

    output_0_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_0_4_ce0_local <= ap_const_logic_1;
        else 
            output_0_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_0_4_d0 <= maxval_2_reg_583;
    output_0_4_we0 <= output_0_4_we0_local;

    output_0_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if ((not((trunc_ln56_reg_579 = ap_const_lv3_0)) and not((trunc_ln56_reg_579 = ap_const_lv3_1)) and not((trunc_ln56_reg_579 = ap_const_lv3_2)) and not((trunc_ln56_reg_579 = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_0))) then 
            output_0_4_we0_local <= ap_const_logic_1;
        else 
            output_0_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_0_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_1_0_ce0 <= output_1_0_ce0_local;

    output_1_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_1_0_ce0_local <= ap_const_logic_1;
        else 
            output_1_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_0_d0 <= maxval_2_reg_583;
    output_1_0_we0 <= output_1_0_we0_local;

    output_1_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_0) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_1))) then 
            output_1_0_we0_local <= ap_const_logic_1;
        else 
            output_1_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_1_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_1_1_ce0 <= output_1_1_ce0_local;

    output_1_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_1_1_ce0_local <= ap_const_logic_1;
        else 
            output_1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_1_d0 <= maxval_2_reg_583;
    output_1_1_we0 <= output_1_1_we0_local;

    output_1_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_1) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_1))) then 
            output_1_1_we0_local <= ap_const_logic_1;
        else 
            output_1_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_2_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_1_2_ce0 <= output_1_2_ce0_local;

    output_1_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_1_2_ce0_local <= ap_const_logic_1;
        else 
            output_1_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_2_d0 <= maxval_2_reg_583;
    output_1_2_we0 <= output_1_2_we0_local;

    output_1_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_2) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_1))) then 
            output_1_2_we0_local <= ap_const_logic_1;
        else 
            output_1_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_3_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_1_3_ce0 <= output_1_3_ce0_local;

    output_1_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_1_3_ce0_local <= ap_const_logic_1;
        else 
            output_1_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_3_d0 <= maxval_2_reg_583;
    output_1_3_we0 <= output_1_3_we0_local;

    output_1_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln56_reg_579 = ap_const_lv3_3) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_1))) then 
            output_1_3_we0_local <= ap_const_logic_1;
        else 
            output_1_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_4_address0 <= zext_ln64_fu_491_p1(9 - 1 downto 0);
    output_1_4_ce0 <= output_1_4_ce0_local;

    output_1_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then 
            output_1_4_ce0_local <= ap_const_logic_1;
        else 
            output_1_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_1_4_d0 <= maxval_2_reg_583;
    output_1_4_we0 <= output_1_4_we0_local;

    output_1_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln55_reg_543_pp0_iter13_reg, trunc_ln56_reg_579)
    begin
        if ((not((trunc_ln56_reg_579 = ap_const_lv3_0)) and not((trunc_ln56_reg_579 = ap_const_lv3_1)) and not((trunc_ln56_reg_579 = ap_const_lv3_2)) and not((trunc_ln56_reg_579 = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln55_reg_543_pp0_iter13_reg = ap_const_lv1_1))) then 
            output_1_4_we0_local <= ap_const_logic_1;
        else 
            output_1_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln55_1_fu_377_p3 <= 
        add_ln55_fu_371_p2 when (icmp_ln56_reg_530_pp0_iter11_reg(0) = '1') else 
        f_fu_100;
    select_ln55_fu_343_p3 <= 
        ap_const_lv9_0 when (icmp_ln56_fu_337_p2(0) = '1') else 
        i_fu_96;
    tmp_1_fu_485_p3 <= (tmp_cast_reg_554_pp0_iter13_reg & lshr_ln_reg_549_pp0_iter13_reg);
    tmp_2_fu_417_p4 <= ((select_ln55_reg_535_pp0_iter11_reg & ap_const_lv1_0) & lshr_ln_fu_388_p4);
    tmp_3_fu_432_p4 <= ((select_ln55_reg_535_pp0_iter11_reg & ap_const_lv1_1) & lshr_ln_fu_388_p4);
    trunc_ln55_fu_384_p1 <= select_ln55_1_fu_377_p3(1 - 1 downto 0);
    trunc_ln56_fu_452_p1 <= grp_fu_351_p2(3 - 1 downto 0);
    v_fu_464_p3 <= 
        input_1_q0 when (trunc_ln55_reg_543(0) = '1') else 
        input_0_q0;
    zext_ln58_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_417_p4),64));
    zext_ln61_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_432_p4),64));
    zext_ln64_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_485_p3),64));
end behav;
