-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_exp_12_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (11 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of ecg_cnn_exp_12_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_7FF : STD_LOGIC_VECTOR (11 downto 0) := "011111111111";

attribute shreg_extract : string;
    signal f_x_lsb_table_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal f_x_lsb_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_x_msb_2_m_1_table_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_x_msb_2_m_1_table_q0 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_table_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_x_msb_1_table_q0 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_reg_417 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_422 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_reg_422_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln191_fu_161_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln191_reg_427 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln191_reg_427_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln191_reg_427_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal f_x_lsb_reg_443 : STD_LOGIC_VECTOR (10 downto 0);
    signal f_x_lsb_reg_443_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_x_msb_2_m_1_reg_449 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_2_m_1_reg_449_pp0_iter2_reg : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_s_reg_455 : STD_LOGIC_VECTOR (18 downto 0);
    signal exp_x_msb_2_lsb_m_1_fu_252_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_2_lsb_m_1_reg_465 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_reg_470 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_reg_470_pp0_iter4_reg : STD_LOGIC_VECTOR (24 downto 0);
    signal y_lo_s_reg_476 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln204_fu_173_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln219_fu_178_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln235_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal f_x_lsb_table_ce0_local : STD_LOGIC;
    signal exp_x_msb_2_m_1_table_ce0_local : STD_LOGIC;
    signal exp_x_msb_1_table_ce0_local : STD_LOGIC;
    signal y_lo_fu_129_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal y_lo_fu_129_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal x_lsb_ind_fu_165_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_msb_ind_2_fu_151_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_x_lsb_m_1_fu_189_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal f_x_msb_2_lsb_fu_204_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal f_x_msb_2_lsb_fu_204_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal f_x_msb_2_lsb_fu_204_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal x_msb_ind_1_fu_183_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_fu_228_p5 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln223_1_fu_238_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln223_fu_225_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln223_fu_242_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln223_2_fu_248_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal y_lo_fu_129_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal y_l_fu_275_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_3_fu_287_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal overf_fu_279_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_295_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_1_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_319_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_335_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_343_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_4_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_327_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_5_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_3_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_6_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_2_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overf_1_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_399_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln259_fu_409_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal f_x_msb_2_lsb_fu_204_p00 : STD_LOGIC_VECTOR (42 downto 0);
    signal f_x_msb_2_lsb_fu_204_p10 : STD_LOGIC_VECTOR (42 downto 0);
    signal y_lo_fu_129_p00 : STD_LOGIC_VECTOR (49 downto 0);
    signal y_lo_fu_129_p10 : STD_LOGIC_VECTOR (49 downto 0);

    component ecg_cnn_mul_25ns_25ns_50_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component ecg_cnn_mul_25ns_18ns_43_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;


    component ecg_cnn_exp_12_3_s_f_x_lsb_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component ecg_cnn_exp_12_3_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component ecg_cnn_exp_12_3_s_exp_x_msb_1_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;



begin
    f_x_lsb_table_U : component ecg_cnn_exp_12_3_s_f_x_lsb_table_ROM_AUTO_1R
    generic map (
        DataWidth => 11,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => f_x_lsb_table_address0,
        ce0 => f_x_lsb_table_ce0_local,
        q0 => f_x_lsb_table_q0);

    exp_x_msb_2_m_1_table_U : component ecg_cnn_exp_12_3_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R
    generic map (
        DataWidth => 25,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_x_msb_2_m_1_table_address0,
        ce0 => exp_x_msb_2_m_1_table_ce0_local,
        q0 => exp_x_msb_2_m_1_table_q0);

    exp_x_msb_1_table_U : component ecg_cnn_exp_12_3_s_exp_x_msb_1_table_ROM_AUTO_1R
    generic map (
        DataWidth => 25,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_x_msb_1_table_address0,
        ce0 => exp_x_msb_1_table_ce0_local,
        q0 => exp_x_msb_1_table_q0);

    mul_25ns_25ns_50_1_0_U285 : component ecg_cnn_mul_25ns_25ns_50_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => y_lo_fu_129_p0,
        din1 => y_lo_fu_129_p1,
        dout => y_lo_fu_129_p2);

    mul_25ns_18ns_43_1_0_U286 : component ecg_cnn_mul_25ns_18ns_43_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 18,
        dout_WIDTH => 43)
    port map (
        din0 => f_x_msb_2_lsb_fu_204_p0,
        din1 => f_x_msb_2_lsb_fu_204_p1,
        dout => f_x_msb_2_lsb_fu_204_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln259_fu_409_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                exp_x_msb_1_reg_470 <= exp_x_msb_1_table_q0;
                exp_x_msb_1_reg_470_pp0_iter4_reg <= exp_x_msb_1_reg_470;
                exp_x_msb_2_lsb_m_1_reg_465 <= exp_x_msb_2_lsb_m_1_fu_252_p2;
                exp_x_msb_2_m_1_reg_449 <= exp_x_msb_2_m_1_table_q0;
                exp_x_msb_2_m_1_reg_449_pp0_iter2_reg <= exp_x_msb_2_m_1_reg_449;
                f_x_lsb_reg_443 <= f_x_lsb_table_q0;
                f_x_lsb_reg_443_pp0_iter2_reg <= f_x_lsb_reg_443;
                tmp_9_reg_422 <= x_int_reg(11 downto 8);
                tmp_9_reg_422_pp0_iter1_reg <= tmp_9_reg_422;
                tmp_reg_417 <= x_int_reg(11 downto 11);
                tmp_reg_417_pp0_iter1_reg <= tmp_reg_417;
                tmp_s_reg_455 <= f_x_msb_2_lsb_fu_204_p2(42 downto 24);
                trunc_ln191_reg_427 <= trunc_ln191_fu_161_p1;
                trunc_ln191_reg_427_pp0_iter1_reg <= trunc_ln191_reg_427;
                trunc_ln191_reg_427_pp0_iter2_reg <= trunc_ln191_reg_427_pp0_iter1_reg;
                y_lo_s_reg_476 <= y_lo_fu_129_p2(49 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    add_ln223_fu_242_p2 <= std_logic_vector(unsigned(zext_ln223_1_fu_238_p1) + unsigned(zext_ln223_fu_225_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln259_fu_409_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln259_fu_409_p3;
        else 
            ap_return <= "XXXXXXXXXXXX";
        end if; 
    end process;

    exp_x_lsb_m_1_fu_189_p4 <= ((trunc_ln191_reg_427_pp0_iter1_reg & ap_const_lv4_0) & f_x_lsb_reg_443);
    exp_x_msb_1_table_address0 <= zext_ln235_fu_220_p1(5 - 1 downto 0);

    exp_x_msb_1_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_x_msb_1_table_ce0_local <= ap_const_logic_1;
        else 
            exp_x_msb_1_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    exp_x_msb_2_lsb_m_1_fu_252_p2 <= std_logic_vector(unsigned(exp_x_msb_2_m_1_reg_449_pp0_iter2_reg) + unsigned(zext_ln223_2_fu_248_p1));
    exp_x_msb_2_m_1_table_address0 <= zext_ln219_fu_178_p1(5 - 1 downto 0);

    exp_x_msb_2_m_1_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            exp_x_msb_2_m_1_table_ce0_local <= ap_const_logic_1;
        else 
            exp_x_msb_2_m_1_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    f_x_lsb_table_address0 <= zext_ln204_fu_173_p1(5 - 1 downto 0);

    f_x_lsb_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            f_x_lsb_table_ce0_local <= ap_const_logic_1;
        else 
            f_x_lsb_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    f_x_msb_2_lsb_fu_204_p0 <= f_x_msb_2_lsb_fu_204_p00(25 - 1 downto 0);
    f_x_msb_2_lsb_fu_204_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_msb_2_m_1_reg_449),43));
    f_x_msb_2_lsb_fu_204_p1 <= f_x_msb_2_lsb_fu_204_p10(18 - 1 downto 0);
    f_x_msb_2_lsb_fu_204_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_lsb_m_1_fu_189_p4),43));
    or_ln245_1_fu_357_p2 <= (tmp_5_fu_303_p3 or tmp_4_fu_295_p3);
    or_ln245_2_fu_363_p2 <= (or_ln245_fu_351_p2 or or_ln245_1_fu_357_p2);
    or_ln245_3_fu_369_p2 <= (tmp_7_fu_319_p3 or tmp_6_fu_311_p3);
    or_ln245_4_fu_375_p2 <= (tmp_11_fu_343_p3 or tmp_10_fu_335_p3);
    or_ln245_5_fu_381_p2 <= (tmp_8_fu_327_p3 or or_ln245_4_fu_375_p2);
    or_ln245_6_fu_387_p2 <= (or_ln245_5_fu_381_p2 or or_ln245_3_fu_369_p2);
    or_ln245_fu_351_p2 <= (tmp_3_fu_287_p3 or overf_fu_279_p3);
    overf_1_fu_393_p2 <= (or_ln245_6_fu_387_p2 or or_ln245_2_fu_363_p2);
    overf_fu_279_p3 <= y_l_fu_275_p2(24 downto 24);
    select_ln259_fu_409_p3 <= 
        ap_const_lv12_7FF when (overf_1_fu_393_p2(0) = '1') else 
        trunc_ln_fu_399_p4;
    shl_ln_fu_228_p5 <= (((trunc_ln191_reg_427_pp0_iter2_reg & ap_const_lv4_0) & f_x_lsb_reg_443_pp0_iter2_reg) & ap_const_lv1_0);
    tmp_10_fu_335_p3 <= y_l_fu_275_p2(17 downto 17);
    tmp_11_fu_343_p3 <= y_l_fu_275_p2(16 downto 16);
    tmp_3_fu_287_p3 <= y_l_fu_275_p2(23 downto 23);
    tmp_4_fu_295_p3 <= y_l_fu_275_p2(22 downto 22);
    tmp_5_fu_303_p3 <= y_l_fu_275_p2(21 downto 21);
    tmp_6_fu_311_p3 <= y_l_fu_275_p2(20 downto 20);
    tmp_7_fu_319_p3 <= y_l_fu_275_p2(19 downto 19);
    tmp_8_fu_327_p3 <= y_l_fu_275_p2(18 downto 18);
    trunc_ln191_fu_161_p1 <= x_int_reg(3 - 1 downto 0);
    trunc_ln_fu_399_p4 <= y_l_fu_275_p2(16 downto 5);
    x_lsb_ind_fu_165_p3 <= (trunc_ln191_fu_161_p1 & ap_const_lv2_0);
    x_msb_ind_1_fu_183_p3 <= (tmp_reg_417_pp0_iter1_reg & tmp_9_reg_422_pp0_iter1_reg);
    x_msb_ind_2_fu_151_p4 <= x_int_reg(7 downto 3);
    y_l_fu_275_p2 <= std_logic_vector(unsigned(exp_x_msb_1_reg_470_pp0_iter4_reg) + unsigned(y_lo_s_reg_476));
    y_lo_fu_129_p0 <= y_lo_fu_129_p00(25 - 1 downto 0);
    y_lo_fu_129_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_msb_2_lsb_m_1_reg_465),50));
    y_lo_fu_129_p1 <= y_lo_fu_129_p10(25 - 1 downto 0);
    y_lo_fu_129_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_msb_1_reg_470),50));
    zext_ln204_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_lsb_ind_fu_165_p3),64));
    zext_ln219_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_msb_ind_2_fu_151_p4),64));
    zext_ln223_1_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_228_p5),20));
    zext_ln223_2_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln223_fu_242_p2),25));
    zext_ln223_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_455),20));
    zext_ln235_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_msb_ind_1_fu_183_p3),64));
end behav;
