-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_dense_linear is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (10 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of ecg_cnn_dense_linear is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_F42 : STD_LOGIC_VECTOR (11 downto 0) := "111101000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv12_12D : STD_LOGIC_VECTOR (11 downto 0) := "000100101101";
    constant ap_const_lv12_BC8 : STD_LOGIC_VECTOR (11 downto 0) := "101111001000";
    constant ap_const_lv12_4AD : STD_LOGIC_VECTOR (11 downto 0) := "010010101101";
    constant ap_const_lv12_E17 : STD_LOGIC_VECTOR (11 downto 0) := "111000010111";
    constant ap_const_lv12_36B : STD_LOGIC_VECTOR (11 downto 0) := "001101101011";
    constant ap_const_lv12_E4D : STD_LOGIC_VECTOR (11 downto 0) := "111001001101";
    constant ap_const_lv12_E44 : STD_LOGIC_VECTOR (11 downto 0) := "111001000100";
    constant ap_const_lv12_EED : STD_LOGIC_VECTOR (11 downto 0) := "111011101101";
    constant ap_const_lv12_3DF : STD_LOGIC_VECTOR (11 downto 0) := "001111011111";
    constant ap_const_lv12_EEF : STD_LOGIC_VECTOR (11 downto 0) := "111011101111";
    constant ap_const_lv12_429 : STD_LOGIC_VECTOR (11 downto 0) := "010000101001";
    constant ap_const_lv12_359 : STD_LOGIC_VECTOR (11 downto 0) := "001101011001";
    constant ap_const_lv12_F9D : STD_LOGIC_VECTOR (11 downto 0) := "111110011101";
    constant ap_const_lv12_3E5 : STD_LOGIC_VECTOR (11 downto 0) := "001111100101";
    constant ap_const_lv12_E90 : STD_LOGIC_VECTOR (11 downto 0) := "111010010000";
    constant ap_const_lv12_EAF : STD_LOGIC_VECTOR (11 downto 0) := "111010101111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln179_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln179_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln181_fu_144 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_sig_allocacmp_phi_ln181_load : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal acc_01_fu_148 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_152 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln179_fu_276_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln_fu_286_p33 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln179_fu_282_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p35 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_362_p33 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_362_p35 : STD_LOGIC_VECTOR (11 downto 0);
    signal acc_fu_454_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_476_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_476_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_476_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_476_p10 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln_fu_286_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln_fu_286_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_362_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_sparsemux_33_4_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (10 downto 0);
        din4 : IN STD_LOGIC_VECTOR (10 downto 0);
        din5 : IN STD_LOGIC_VECTOR (10 downto 0);
        din6 : IN STD_LOGIC_VECTOR (10 downto 0);
        din7 : IN STD_LOGIC_VECTOR (10 downto 0);
        din8 : IN STD_LOGIC_VECTOR (10 downto 0);
        din9 : IN STD_LOGIC_VECTOR (10 downto 0);
        din10 : IN STD_LOGIC_VECTOR (10 downto 0);
        din11 : IN STD_LOGIC_VECTOR (10 downto 0);
        din12 : IN STD_LOGIC_VECTOR (10 downto 0);
        din13 : IN STD_LOGIC_VECTOR (10 downto 0);
        din14 : IN STD_LOGIC_VECTOR (10 downto 0);
        din15 : IN STD_LOGIC_VECTOR (10 downto 0);
        def : IN STD_LOGIC_VECTOR (10 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component ecg_cnn_sparsemux_33_4_12_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        din3 : IN STD_LOGIC_VECTOR (11 downto 0);
        din4 : IN STD_LOGIC_VECTOR (11 downto 0);
        din5 : IN STD_LOGIC_VECTOR (11 downto 0);
        din6 : IN STD_LOGIC_VECTOR (11 downto 0);
        din7 : IN STD_LOGIC_VECTOR (11 downto 0);
        din8 : IN STD_LOGIC_VECTOR (11 downto 0);
        din9 : IN STD_LOGIC_VECTOR (11 downto 0);
        din10 : IN STD_LOGIC_VECTOR (11 downto 0);
        din11 : IN STD_LOGIC_VECTOR (11 downto 0);
        din12 : IN STD_LOGIC_VECTOR (11 downto 0);
        din13 : IN STD_LOGIC_VECTOR (11 downto 0);
        din14 : IN STD_LOGIC_VECTOR (11 downto 0);
        din15 : IN STD_LOGIC_VECTOR (11 downto 0);
        def : IN STD_LOGIC_VECTOR (11 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component ecg_cnn_mac_muladd_12s_11ns_21ns_21_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        din2 : IN STD_LOGIC_VECTOR (20 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component ecg_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_11_1_1_U264 : component ecg_cnn_sparsemux_33_4_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 11,
        CASE1 => "0001",
        din1_WIDTH => 11,
        CASE2 => "0010",
        din2_WIDTH => 11,
        CASE3 => "0011",
        din3_WIDTH => 11,
        CASE4 => "0100",
        din4_WIDTH => 11,
        CASE5 => "0101",
        din5_WIDTH => 11,
        CASE6 => "0110",
        din6_WIDTH => 11,
        CASE7 => "0111",
        din7_WIDTH => 11,
        CASE8 => "1000",
        din8_WIDTH => 11,
        CASE9 => "1001",
        din9_WIDTH => 11,
        CASE10 => "1010",
        din10_WIDTH => 11,
        CASE11 => "1011",
        din11_WIDTH => 11,
        CASE12 => "1100",
        din12_WIDTH => 11,
        CASE13 => "1101",
        din13_WIDTH => 11,
        CASE14 => "1110",
        din14_WIDTH => 11,
        CASE15 => "1111",
        din15_WIDTH => 11,
        def_WIDTH => 11,
        sel_WIDTH => 4,
        dout_WIDTH => 11)
    port map (
        din0 => input_0_val,
        din1 => input_1_val,
        din2 => input_2_val,
        din3 => input_3_val,
        din4 => input_4_val,
        din5 => input_5_val,
        din6 => input_6_val,
        din7 => input_7_val,
        din8 => input_8_val,
        din9 => input_9_val,
        din10 => input_10_val,
        din11 => input_11_val,
        din12 => input_12_val,
        din13 => input_13_val,
        din14 => input_14_val,
        din15 => input_15_val,
        def => sext_ln_fu_286_p33,
        sel => trunc_ln179_fu_282_p1,
        dout => sext_ln_fu_286_p35);

    sparsemux_33_4_12_1_1_x_U265 : component ecg_cnn_sparsemux_33_4_12_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 12,
        CASE1 => "0001",
        din1_WIDTH => 12,
        CASE2 => "0010",
        din2_WIDTH => 12,
        CASE3 => "0011",
        din3_WIDTH => 12,
        CASE4 => "0100",
        din4_WIDTH => 12,
        CASE5 => "0101",
        din5_WIDTH => 12,
        CASE6 => "0110",
        din6_WIDTH => 12,
        CASE7 => "0111",
        din7_WIDTH => 12,
        CASE8 => "1000",
        din8_WIDTH => 12,
        CASE9 => "1001",
        din9_WIDTH => 12,
        CASE10 => "1010",
        din10_WIDTH => 12,
        CASE11 => "1011",
        din11_WIDTH => 12,
        CASE12 => "1100",
        din12_WIDTH => 12,
        CASE13 => "1101",
        din13_WIDTH => 12,
        CASE14 => "1110",
        din14_WIDTH => 12,
        CASE15 => "1111",
        din15_WIDTH => 12,
        def_WIDTH => 12,
        sel_WIDTH => 4,
        dout_WIDTH => 12)
    port map (
        din0 => ap_const_lv12_12D,
        din1 => ap_const_lv12_BC8,
        din2 => ap_const_lv12_4AD,
        din3 => ap_const_lv12_E17,
        din4 => ap_const_lv12_36B,
        din5 => ap_const_lv12_E4D,
        din6 => ap_const_lv12_E44,
        din7 => ap_const_lv12_EED,
        din8 => ap_const_lv12_3DF,
        din9 => ap_const_lv12_EEF,
        din10 => ap_const_lv12_429,
        din11 => ap_const_lv12_359,
        din12 => ap_const_lv12_F9D,
        din13 => ap_const_lv12_3E5,
        din14 => ap_const_lv12_E90,
        din15 => ap_const_lv12_EAF,
        def => tmp_s_fu_362_p33,
        sel => trunc_ln179_fu_282_p1,
        dout => tmp_s_fu_362_p35);

    mac_muladd_12s_11ns_21ns_21_4_1_U266 : component ecg_cnn_mac_muladd_12s_11ns_21ns_21_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 11,
        din2_WIDTH => 21,
        dout_WIDTH => 21)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_s_fu_362_p35,
        din1 => grp_fu_476_p1,
        din2 => grp_fu_476_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_476_p3);

    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    acc_01_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                acc_01_fu_148 <= ap_const_lv12_F42;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                acc_01_fu_148 <= acc_fu_454_p1(20 downto 9);
            end if; 
        end if;
    end process;

    i_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln179_fu_270_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_152 <= add_ln179_fu_276_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_152 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    phi_ln181_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                phi_ln181_fu_144 <= ap_const_lv12_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                phi_ln181_fu_144 <= acc_fu_454_p1(20 downto 9);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln179_reg_506 <= icmp_ln179_fu_270_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    acc_fu_454_p1 <= grp_fu_476_p3;
    add_ln179_fu_276_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln179_reg_506)
    begin
        if (((icmp_ln179_reg_506 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_sig_allocacmp_phi_ln181_load;

    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i_fu_152)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_152;
        end if; 
    end process;


    ap_sig_allocacmp_phi_ln181_load_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, phi_ln181_fu_144, ap_block_pp0_stage1, acc_fu_454_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_phi_ln181_load <= acc_fu_454_p1(20 downto 9);
        else 
            ap_sig_allocacmp_phi_ln181_load <= phi_ln181_fu_144;
        end if; 
    end process;

    grp_fu_476_p1 <= grp_fu_476_p10(11 - 1 downto 0);
    grp_fu_476_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln_fu_286_p35),21));
    grp_fu_476_p2 <= (acc_01_fu_148 & ap_const_lv9_0);
    icmp_ln179_fu_270_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv5_10) else "0";
    sext_ln_fu_286_p33 <= "XXXXXXXXXXX";
    tmp_s_fu_362_p33 <= "XXXXXXXXXXXX";
    trunc_ln179_fu_282_p1 <= ap_sig_allocacmp_i_3(4 - 1 downto 0);
end behav;
