-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_gap is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    input_0_ce0 : OUT STD_LOGIC;
    input_0_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    input_1_ce0 : OUT STD_LOGIC;
    input_1_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    input_2_ce0 : OUT STD_LOGIC;
    input_2_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    input_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    input_3_ce0 : OUT STD_LOGIC;
    input_3_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
    output_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_0_ap_vld : OUT STD_LOGIC;
    output_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_1_ap_vld : OUT STD_LOGIC;
    output_2 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_2_ap_vld : OUT STD_LOGIC;
    output_3 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_3_ap_vld : OUT STD_LOGIC;
    output_4 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_4_ap_vld : OUT STD_LOGIC;
    output_5 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_5_ap_vld : OUT STD_LOGIC;
    output_6 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_6_ap_vld : OUT STD_LOGIC;
    output_7 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_7_ap_vld : OUT STD_LOGIC;
    output_8 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_8_ap_vld : OUT STD_LOGIC;
    output_9 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_9_ap_vld : OUT STD_LOGIC;
    output_10 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_10_ap_vld : OUT STD_LOGIC;
    output_11 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_11_ap_vld : OUT STD_LOGIC;
    output_12 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_12_ap_vld : OUT STD_LOGIC;
    output_13 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_13_ap_vld : OUT STD_LOGIC;
    output_14 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_14_ap_vld : OUT STD_LOGIC;
    output_15 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_15_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_gap is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln115_fu_255_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln115_reg_353 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln115_fu_261_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln115_reg_358 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln115_1_fu_265_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln115_1_reg_363 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_reg_368 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_idle : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0 : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0 : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0 : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0 : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out_ap_vld : STD_LOGIC;
    signal grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln115_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal f_fu_106 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_gap_Pipeline_VITIS_LOOP_117_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lshr_ln : IN STD_LOGIC_VECTOR (1 downto 0);
        input_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        input_0_ce0 : OUT STD_LOGIC;
        input_0_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
        input_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        input_1_ce0 : OUT STD_LOGIC;
        input_1_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
        input_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        input_2_ce0 : OUT STD_LOGIC;
        input_2_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
        input_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        input_3_ce0 : OUT STD_LOGIC;
        input_3_q0 : IN STD_LOGIC_VECTOR (10 downto 0);
        empty : IN STD_LOGIC_VECTOR (1 downto 0);
        sum_out : OUT STD_LOGIC_VECTOR (11 downto 0);
        sum_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226 : component ecg_cnn_gap_Pipeline_VITIS_LOOP_117_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start,
        ap_done => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done,
        ap_idle => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_idle,
        ap_ready => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready,
        lshr_ln => lshr_ln_reg_368,
        input_0_address0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0,
        input_0_ce0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0,
        input_0_q0 => input_0_q0,
        input_1_address0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0,
        input_1_ce0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0,
        input_1_q0 => input_1_q0,
        input_2_address0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0,
        input_2_ce0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0,
        input_2_q0 => input_2_q0,
        input_3_address0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0,
        input_3_ce0 => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0,
        input_3_q0 => input_3_q0,
        empty => trunc_ln115_1_reg_363,
        sum_out => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out,
        sum_out_ap_vld => grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln115_fu_249_p2 = ap_const_lv1_0))) then 
                    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready = ap_const_logic_1)) then 
                    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    f_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                f_fu_106 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                f_fu_106 <= add_ln115_reg_353;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln115_reg_353 <= add_ln115_fu_255_p2;
                lshr_ln_reg_368 <= f_fu_106(3 downto 2);
                trunc_ln115_1_reg_363 <= trunc_ln115_1_fu_265_p1;
                trunc_ln115_reg_358 <= trunc_ln115_fu_261_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done, icmp_ln115_fu_249_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln115_fu_249_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln115_fu_255_p2 <= std_logic_vector(unsigned(f_fu_106) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done)
    begin
        if ((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln115_fu_249_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln115_fu_249_p2 = ap_const_lv1_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln115_fu_249_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln115_fu_249_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg;
    icmp_ln115_fu_249_p2 <= "1" when (f_fu_106 = ap_const_lv5_10) else "0";
    input_0_address0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0;
    input_0_ce0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0;
    input_1_address0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0;
    input_1_ce0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0;
    input_2_address0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0;
    input_2_ce0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0;
    input_3_address0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0;
    input_3_ce0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0;
    output_0 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_0_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_0_ap_vld <= ap_const_logic_1;
        else 
            output_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_1 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;
    output_10 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_10_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_A) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_10_ap_vld <= ap_const_logic_1;
        else 
            output_10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_11 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_11_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_B) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_11_ap_vld <= ap_const_logic_1;
        else 
            output_11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_12 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_12_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_C) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_12_ap_vld <= ap_const_logic_1;
        else 
            output_12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_13 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_13_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_D) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_13_ap_vld <= ap_const_logic_1;
        else 
            output_13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_14 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_14_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_E) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_14_ap_vld <= ap_const_logic_1;
        else 
            output_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_15 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_15_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_F) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_15_ap_vld <= ap_const_logic_1;
        else 
            output_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    output_1_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_1_ap_vld <= ap_const_logic_1;
        else 
            output_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_2 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_2_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_2_ap_vld <= ap_const_logic_1;
        else 
            output_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_3 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_3_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_3) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_3_ap_vld <= ap_const_logic_1;
        else 
            output_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_4 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_4_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_4_ap_vld <= ap_const_logic_1;
        else 
            output_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_5 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_5_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_5) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_5_ap_vld <= ap_const_logic_1;
        else 
            output_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_6 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_6_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_6) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_6_ap_vld <= ap_const_logic_1;
        else 
            output_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_7 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_7_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_7) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_7_ap_vld <= ap_const_logic_1;
        else 
            output_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_8 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_8_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_8) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_8_ap_vld <= ap_const_logic_1;
        else 
            output_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_9 <= grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

    output_9_ap_vld_assign_proc : process(trunc_ln115_reg_358, ap_CS_fsm_state4)
    begin
        if (((trunc_ln115_reg_358 = ap_const_lv4_9) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_9_ap_vld <= ap_const_logic_1;
        else 
            output_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln115_1_fu_265_p1 <= f_fu_106(2 - 1 downto 0);
    trunc_ln115_fu_261_p1 <= f_fu_106(4 - 1 downto 0);
end behav;
