-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_3_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_3_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001101101", 1 => "11110111001", 2 => "00010111011", 3 => "11111011000", 
    4 => "00010001001", 5 => "00011100110", 6 => "11110001110", 7 => "00001011011", 
    8 => "11101000001", 9 => "10110110000", 10 => "00001110000", 11 => "00000110000", 
    12 => "11010100000", 13 => "00111000000", 14 => "11111001001", 15 => "11100000010", 
    16 => "11110100110", 17 => "10110010101", 18 => "00010100010", 19 => "00011011000", 
    20 => "11100101110", 21 => "00101001111", 22 => "11011111010", 23 => "11011110110", 
    24 => "11001010010", 25 => "00010011110", 26 => "11001100101", 27 => "11101110000", 
    28 => "11100111010", 29 => "11110011101", 30 => "00000000001", 31 => "00001001010", 
    32 => "00000100100", 33 => "10100111001", 34 => "00001100111", 35 => "11111010111", 
    36 => "11100111101", 37 => "11111010111", 38 => "00010110101", 39 => "00001101101", 
    40 => "00001110110", 41 => "11000111000", 42 => "11111000000", 43 => "00010010100", 
    44 => "11111101001", 45 => "10111101100", 46 => "00010101111", 47 => "00001110101", 
    48 => "00010011110", 49 => "00001010101", 50 => "00010011110", 51 => "11101010100", 
    52 => "11111110100", 53 => "10110010101", 54 => "00011001111", 55 => "11101010001", 
    56 => "11010110001", 57 => "01000010101", 58 => "11100101011", 59 => "11001100101", 
    60 => "11000100111", 61 => "01000001110", 62 => "11011001101", 63 => "11010001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

