-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "111111101111", 1 => "000001010011", 2 => "111110110100", 3 => "111110110100", 
    4 => "111101100110", 5 => "001100101011", 6 => "111100001010", 7 => "111101011010", 
    8 => "111110111110", 9 => "101111001001", 10 => "000000110101", 11 => "000000010000", 
    12 => "111111101100", 13 => "000101101101", 14 => "000001001001", 15 => "111101000011", 
    16 => "111110010001", 17 => "110000101100", 18 => "111101111100", 19 => "111110011100", 
    20 => "000011011100", 21 => "001001011001", 22 => "000001001011", 23 => "111100001000", 
    24 => "111110100100", 25 => "001001000011", 26 => "000001011011", 27 => "000001101011", 
    28 => "111101110010", 29 => "111100100001", 30 => "111110011001", 31 => "111100001100", 
    32 => "111110001000", 33 => "101111110001", 34 => "000000000110", 35 => "111110000111", 
    36 => "000010001110", 37 => "000000000101", 38 => "111111101111", 39 => "111110110001", 
    40 => "000000111101", 41 => "110000101101", 42 => "111111001110", 43 => "111111001001", 
    44 => "111110100000", 45 => "110000001111", 46 => "111110000100", 47 => "111110100100", 
    48 => "000010000110", 49 => "111111101110", 50 => "111100100110", 51 => "111110111010", 
    52 => "111101000010", 53 => "101110111110", 54 => "000000000000", 55 => "000001111101", 
    56 => "000011100101", 57 => "001001101100", 58 => "111110100001", 59 => "111111111101", 
    60 => "000010111000", 61 => "001000011001", 62 => "000001101001", 63 => "111111110001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

