// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_maxpool (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_0_address1,
        input_0_ce1,
        input_0_q1,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_1_address1,
        input_1_ce1,
        input_1_q1,
        output_0_0_address0,
        output_0_0_ce0,
        output_0_0_we0,
        output_0_0_d0,
        output_0_1_address0,
        output_0_1_ce0,
        output_0_1_we0,
        output_0_1_d0,
        output_0_2_address0,
        output_0_2_ce0,
        output_0_2_we0,
        output_0_2_d0,
        output_0_3_address0,
        output_0_3_ce0,
        output_0_3_we0,
        output_0_3_d0,
        output_0_4_address0,
        output_0_4_ce0,
        output_0_4_we0,
        output_0_4_d0,
        output_1_0_address0,
        output_1_0_ce0,
        output_1_0_we0,
        output_1_0_d0,
        output_1_1_address0,
        output_1_1_ce0,
        output_1_1_we0,
        output_1_1_d0,
        output_1_2_address0,
        output_1_2_ce0,
        output_1_2_we0,
        output_1_2_d0,
        output_1_3_address0,
        output_1_3_ce0,
        output_1_3_we0,
        output_1_3_d0,
        output_1_4_address0,
        output_1_4_ce0,
        output_1_4_we0,
        output_1_4_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] input_0_address0;
output   input_0_ce0;
input  [10:0] input_0_q0;
output  [11:0] input_0_address1;
output   input_0_ce1;
input  [10:0] input_0_q1;
output  [11:0] input_1_address0;
output   input_1_ce0;
input  [10:0] input_1_q0;
output  [11:0] input_1_address1;
output   input_1_ce1;
input  [10:0] input_1_q1;
output  [8:0] output_0_0_address0;
output   output_0_0_ce0;
output   output_0_0_we0;
output  [10:0] output_0_0_d0;
output  [8:0] output_0_1_address0;
output   output_0_1_ce0;
output   output_0_1_we0;
output  [10:0] output_0_1_d0;
output  [8:0] output_0_2_address0;
output   output_0_2_ce0;
output   output_0_2_we0;
output  [10:0] output_0_2_d0;
output  [8:0] output_0_3_address0;
output   output_0_3_ce0;
output   output_0_3_we0;
output  [10:0] output_0_3_d0;
output  [8:0] output_0_4_address0;
output   output_0_4_ce0;
output   output_0_4_we0;
output  [10:0] output_0_4_d0;
output  [8:0] output_1_0_address0;
output   output_1_0_ce0;
output   output_1_0_we0;
output  [10:0] output_1_0_d0;
output  [8:0] output_1_1_address0;
output   output_1_1_ce0;
output   output_1_1_we0;
output  [10:0] output_1_1_d0;
output  [8:0] output_1_2_address0;
output   output_1_2_ce0;
output   output_1_2_we0;
output  [10:0] output_1_2_d0;
output  [8:0] output_1_3_address0;
output   output_1_3_ce0;
output   output_1_3_we0;
output  [10:0] output_1_3_d0;
output  [8:0] output_1_4_address0;
output   output_1_4_ce0;
output   output_1_4_we0;
output  [10:0] output_1_4_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_317_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln56_fu_337_p2;
reg   [0:0] icmp_ln56_reg_530;
reg   [0:0] icmp_ln56_reg_530_pp0_iter2_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter3_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter4_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter5_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter6_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter7_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter8_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter9_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter10_reg;
reg   [0:0] icmp_ln56_reg_530_pp0_iter11_reg;
wire   [8:0] select_ln55_fu_343_p3;
reg   [8:0] select_ln55_reg_535;
reg   [8:0] select_ln55_reg_535_pp0_iter2_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter3_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter4_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter5_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter6_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter7_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter8_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter9_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter10_reg;
reg   [8:0] select_ln55_reg_535_pp0_iter11_reg;
wire   [0:0] trunc_ln55_fu_384_p1;
reg   [0:0] trunc_ln55_reg_543;
reg   [0:0] trunc_ln55_reg_543_pp0_iter13_reg;
wire   [1:0] lshr_ln_fu_388_p4;
reg   [1:0] lshr_ln_reg_549;
reg   [1:0] lshr_ln_reg_549_pp0_iter13_reg;
reg   [6:0] tmp_cast_reg_554;
reg   [6:0] tmp_cast_reg_554_pp0_iter13_reg;
wire   [2:0] trunc_ln56_fu_452_p1;
reg   [2:0] trunc_ln56_reg_579;
wire   [10:0] maxval_2_fu_477_p3;
reg   [10:0] maxval_2_reg_583;
wire   [63:0] zext_ln58_fu_426_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln61_fu_441_p1;
wire   [63:0] zext_ln64_fu_491_p1;
reg   [8:0] i_fu_96;
wire   [8:0] add_ln56_fu_357_p2;
wire    ap_loop_init;
reg   [3:0] f_fu_100;
wire   [3:0] select_ln55_1_fu_377_p3;
reg   [11:0] indvar_flatten_fu_104;
wire   [11:0] add_ln55_1_fu_323_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg    input_0_ce1_local;
reg    input_0_ce0_local;
reg    input_1_ce1_local;
reg    input_1_ce0_local;
reg    output_0_3_we0_local;
reg    output_0_3_ce0_local;
reg    output_0_2_we0_local;
reg    output_0_2_ce0_local;
reg    output_0_1_we0_local;
reg    output_0_1_ce0_local;
reg    output_0_0_we0_local;
reg    output_0_0_ce0_local;
reg    output_0_4_we0_local;
reg    output_0_4_ce0_local;
reg    output_1_3_we0_local;
reg    output_1_3_ce0_local;
reg    output_1_2_we0_local;
reg    output_1_2_ce0_local;
reg    output_1_1_we0_local;
reg    output_1_1_ce0_local;
reg    output_1_0_we0_local;
reg    output_1_0_ce0_local;
reg    output_1_4_we0_local;
reg    output_1_4_ce0_local;
wire   [3:0] grp_fu_351_p1;
wire   [3:0] add_ln55_fu_371_p2;
wire   [8:0] mul_ln56_fu_401_p0;
wire   [10:0] mul_ln56_fu_401_p1;
wire   [18:0] mul_ln56_fu_401_p2;
wire   [11:0] tmp_2_fu_417_p4;
wire   [11:0] tmp_3_fu_432_p4;
wire   [2:0] grp_fu_351_p2;
wire   [10:0] v_fu_464_p3;
wire   [10:0] maxval_fu_457_p3;
wire   [0:0] icmp_ln62_fu_471_p2;
wire   [8:0] tmp_1_fu_485_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [18:0] mul_ln56_fu_401_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 i_fu_96 = 9'd0;
#0 f_fu_100 = 4'd0;
#0 indvar_flatten_fu_104 = 12'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_urem_9ns_4ns_3_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_9ns_4ns_3_13_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln55_fu_343_p3),
    .din1(grp_fu_351_p1),
    .ce(1'b1),
    .dout(grp_fu_351_p2)
);

ecg_cnn_mul_9ns_11ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
mul_9ns_11ns_19_1_1_U26(
    .din0(mul_ln56_fu_401_p0),
    .din1(mul_ln56_fu_401_p1),
    .dout(mul_ln56_fu_401_p2)
);

ecg_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            f_fu_100 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
            f_fu_100 <= select_ln55_1_fu_377_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_96 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_96 <= add_ln56_fu_357_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_317_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_104 <= add_ln55_1_fu_323_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_104 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln56_reg_530_pp0_iter10_reg <= icmp_ln56_reg_530_pp0_iter9_reg;
        icmp_ln56_reg_530_pp0_iter11_reg <= icmp_ln56_reg_530_pp0_iter10_reg;
        icmp_ln56_reg_530_pp0_iter2_reg <= icmp_ln56_reg_530;
        icmp_ln56_reg_530_pp0_iter3_reg <= icmp_ln56_reg_530_pp0_iter2_reg;
        icmp_ln56_reg_530_pp0_iter4_reg <= icmp_ln56_reg_530_pp0_iter3_reg;
        icmp_ln56_reg_530_pp0_iter5_reg <= icmp_ln56_reg_530_pp0_iter4_reg;
        icmp_ln56_reg_530_pp0_iter6_reg <= icmp_ln56_reg_530_pp0_iter5_reg;
        icmp_ln56_reg_530_pp0_iter7_reg <= icmp_ln56_reg_530_pp0_iter6_reg;
        icmp_ln56_reg_530_pp0_iter8_reg <= icmp_ln56_reg_530_pp0_iter7_reg;
        icmp_ln56_reg_530_pp0_iter9_reg <= icmp_ln56_reg_530_pp0_iter8_reg;
        lshr_ln_reg_549 <= {{select_ln55_1_fu_377_p3[2:1]}};
        lshr_ln_reg_549_pp0_iter13_reg <= lshr_ln_reg_549;
        maxval_2_reg_583 <= maxval_2_fu_477_p3;
        select_ln55_reg_535_pp0_iter10_reg <= select_ln55_reg_535_pp0_iter9_reg;
        select_ln55_reg_535_pp0_iter11_reg <= select_ln55_reg_535_pp0_iter10_reg;
        select_ln55_reg_535_pp0_iter2_reg <= select_ln55_reg_535;
        select_ln55_reg_535_pp0_iter3_reg <= select_ln55_reg_535_pp0_iter2_reg;
        select_ln55_reg_535_pp0_iter4_reg <= select_ln55_reg_535_pp0_iter3_reg;
        select_ln55_reg_535_pp0_iter5_reg <= select_ln55_reg_535_pp0_iter4_reg;
        select_ln55_reg_535_pp0_iter6_reg <= select_ln55_reg_535_pp0_iter5_reg;
        select_ln55_reg_535_pp0_iter7_reg <= select_ln55_reg_535_pp0_iter6_reg;
        select_ln55_reg_535_pp0_iter8_reg <= select_ln55_reg_535_pp0_iter7_reg;
        select_ln55_reg_535_pp0_iter9_reg <= select_ln55_reg_535_pp0_iter8_reg;
        tmp_cast_reg_554 <= {{mul_ln56_fu_401_p2[18:12]}};
        tmp_cast_reg_554_pp0_iter13_reg <= tmp_cast_reg_554;
        trunc_ln55_reg_543 <= trunc_ln55_fu_384_p1;
        trunc_ln55_reg_543_pp0_iter13_reg <= trunc_ln55_reg_543;
        trunc_ln56_reg_579 <= trunc_ln56_fu_452_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln56_reg_530 <= icmp_ln56_fu_337_p2;
        select_ln55_reg_535 <= select_ln55_fu_343_p3;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_317_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        input_0_ce0_local = 1'b1;
    end else begin
        input_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        input_0_ce1_local = 1'b1;
    end else begin
        input_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        input_1_ce0_local = 1'b1;
    end else begin
        input_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        input_1_ce1_local = 1'b1;
    end else begin
        input_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_0_0_ce0_local = 1'b1;
    end else begin
        output_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd0) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd0))) begin
        output_0_0_we0_local = 1'b1;
    end else begin
        output_0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_0_1_ce0_local = 1'b1;
    end else begin
        output_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd1) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd0))) begin
        output_0_1_we0_local = 1'b1;
    end else begin
        output_0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_0_2_ce0_local = 1'b1;
    end else begin
        output_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd2) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd0))) begin
        output_0_2_we0_local = 1'b1;
    end else begin
        output_0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_0_3_ce0_local = 1'b1;
    end else begin
        output_0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd3) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd0))) begin
        output_0_3_we0_local = 1'b1;
    end else begin
        output_0_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_0_4_ce0_local = 1'b1;
    end else begin
        output_0_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln56_reg_579 == 3'd0) & ~(trunc_ln56_reg_579 == 3'd1) & ~(trunc_ln56_reg_579 == 3'd2) & ~(trunc_ln56_reg_579 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd0))) begin
        output_0_4_we0_local = 1'b1;
    end else begin
        output_0_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_1_0_ce0_local = 1'b1;
    end else begin
        output_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd0) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd1))) begin
        output_1_0_we0_local = 1'b1;
    end else begin
        output_1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_1_1_ce0_local = 1'b1;
    end else begin
        output_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd1) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd1))) begin
        output_1_1_we0_local = 1'b1;
    end else begin
        output_1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_1_2_ce0_local = 1'b1;
    end else begin
        output_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd2) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd1))) begin
        output_1_2_we0_local = 1'b1;
    end else begin
        output_1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_1_3_ce0_local = 1'b1;
    end else begin
        output_1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln56_reg_579 == 3'd3) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd1))) begin
        output_1_3_we0_local = 1'b1;
    end else begin
        output_1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        output_1_4_ce0_local = 1'b1;
    end else begin
        output_1_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln56_reg_579 == 3'd0) & ~(trunc_ln56_reg_579 == 3'd1) & ~(trunc_ln56_reg_579 == 3'd2) & ~(trunc_ln56_reg_579 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln55_reg_543_pp0_iter13_reg == 1'd1))) begin
        output_1_4_we0_local = 1'b1;
    end else begin
        output_1_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_1_fu_323_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln55_fu_371_p2 = (f_fu_100 + 4'd1);

assign add_ln56_fu_357_p2 = (select_ln55_fu_343_p3 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_351_p1 = 9'd5;

assign icmp_ln55_fu_317_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2856) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_337_p2 = ((i_fu_96 == 9'd357) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_471_p2 = ((v_fu_464_p3 > maxval_fu_457_p3) ? 1'b1 : 1'b0);

assign input_0_address0 = zext_ln61_fu_441_p1;

assign input_0_address1 = zext_ln58_fu_426_p1;

assign input_0_ce0 = input_0_ce0_local;

assign input_0_ce1 = input_0_ce1_local;

assign input_1_address0 = zext_ln61_fu_441_p1;

assign input_1_address1 = zext_ln58_fu_426_p1;

assign input_1_ce0 = input_1_ce0_local;

assign input_1_ce1 = input_1_ce1_local;

assign lshr_ln_fu_388_p4 = {{select_ln55_1_fu_377_p3[2:1]}};

assign maxval_2_fu_477_p3 = ((icmp_ln62_fu_471_p2[0:0] == 1'b1) ? v_fu_464_p3 : maxval_fu_457_p3);

assign maxval_fu_457_p3 = ((trunc_ln55_reg_543[0:0] == 1'b1) ? input_1_q1 : input_0_q1);

assign mul_ln56_fu_401_p0 = mul_ln56_fu_401_p00;

assign mul_ln56_fu_401_p00 = select_ln55_reg_535_pp0_iter11_reg;

assign mul_ln56_fu_401_p1 = 19'd820;

assign output_0_0_address0 = zext_ln64_fu_491_p1;

assign output_0_0_ce0 = output_0_0_ce0_local;

assign output_0_0_d0 = maxval_2_reg_583;

assign output_0_0_we0 = output_0_0_we0_local;

assign output_0_1_address0 = zext_ln64_fu_491_p1;

assign output_0_1_ce0 = output_0_1_ce0_local;

assign output_0_1_d0 = maxval_2_reg_583;

assign output_0_1_we0 = output_0_1_we0_local;

assign output_0_2_address0 = zext_ln64_fu_491_p1;

assign output_0_2_ce0 = output_0_2_ce0_local;

assign output_0_2_d0 = maxval_2_reg_583;

assign output_0_2_we0 = output_0_2_we0_local;

assign output_0_3_address0 = zext_ln64_fu_491_p1;

assign output_0_3_ce0 = output_0_3_ce0_local;

assign output_0_3_d0 = maxval_2_reg_583;

assign output_0_3_we0 = output_0_3_we0_local;

assign output_0_4_address0 = zext_ln64_fu_491_p1;

assign output_0_4_ce0 = output_0_4_ce0_local;

assign output_0_4_d0 = maxval_2_reg_583;

assign output_0_4_we0 = output_0_4_we0_local;

assign output_1_0_address0 = zext_ln64_fu_491_p1;

assign output_1_0_ce0 = output_1_0_ce0_local;

assign output_1_0_d0 = maxval_2_reg_583;

assign output_1_0_we0 = output_1_0_we0_local;

assign output_1_1_address0 = zext_ln64_fu_491_p1;

assign output_1_1_ce0 = output_1_1_ce0_local;

assign output_1_1_d0 = maxval_2_reg_583;

assign output_1_1_we0 = output_1_1_we0_local;

assign output_1_2_address0 = zext_ln64_fu_491_p1;

assign output_1_2_ce0 = output_1_2_ce0_local;

assign output_1_2_d0 = maxval_2_reg_583;

assign output_1_2_we0 = output_1_2_we0_local;

assign output_1_3_address0 = zext_ln64_fu_491_p1;

assign output_1_3_ce0 = output_1_3_ce0_local;

assign output_1_3_d0 = maxval_2_reg_583;

assign output_1_3_we0 = output_1_3_we0_local;

assign output_1_4_address0 = zext_ln64_fu_491_p1;

assign output_1_4_ce0 = output_1_4_ce0_local;

assign output_1_4_d0 = maxval_2_reg_583;

assign output_1_4_we0 = output_1_4_we0_local;

assign select_ln55_1_fu_377_p3 = ((icmp_ln56_reg_530_pp0_iter11_reg[0:0] == 1'b1) ? add_ln55_fu_371_p2 : f_fu_100);

assign select_ln55_fu_343_p3 = ((icmp_ln56_fu_337_p2[0:0] == 1'b1) ? 9'd0 : i_fu_96);

assign tmp_1_fu_485_p3 = {{tmp_cast_reg_554_pp0_iter13_reg}, {lshr_ln_reg_549_pp0_iter13_reg}};

assign tmp_2_fu_417_p4 = {{{select_ln55_reg_535_pp0_iter11_reg}, {1'd0}}, {lshr_ln_fu_388_p4}};

assign tmp_3_fu_432_p4 = {{{select_ln55_reg_535_pp0_iter11_reg}, {1'd1}}, {lshr_ln_fu_388_p4}};

assign trunc_ln55_fu_384_p1 = select_ln55_1_fu_377_p3[0:0];

assign trunc_ln56_fu_452_p1 = grp_fu_351_p2[2:0];

assign v_fu_464_p3 = ((trunc_ln55_reg_543[0:0] == 1'b1) ? input_1_q0 : input_0_q0);

assign zext_ln58_fu_426_p1 = tmp_2_fu_417_p4;

assign zext_ln61_fu_441_p1 = tmp_3_fu_432_p4;

assign zext_ln64_fu_491_p1 = tmp_1_fu_485_p3;

endmodule //ecg_cnn_maxpool
