

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "34", "38", "147", "151", "162", "167", "173", "174", "175", "176"],
		"CDFG" : "ecg_cnn",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "60677", "EstimateLatencyMax" : "60677",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "INPUT_r", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "INPUT_r", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "OUTPUT_r", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "OUTPUT_r_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "OUTPUT_r_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "OUTPUT_r_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "input_r_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "w_local_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_4", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_5", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_conv1d_relu_fu_406", "Port" : "w_local_6", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "w_local_80_0_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_0_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_0_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_0_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_0_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_0_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_0_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_0_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_0_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_0_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_1_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_1_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_1_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_1_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_1_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_1_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_1_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_1_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_1_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_1_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_2_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_2_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_2_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_2_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_2_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_2_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_2_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_2_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_2_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_2_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_3_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_3_0", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_3_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_3_1", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_3_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_3_2", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_3_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_3_3", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_80_3_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_conv1d_relu2_fu_448", "Port" : "w_local_80_3_4", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "w_local_82_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "151", "SubInstance" : "grp_dense_relu_fu_530", "Port" : "w_local_82_0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "w_local_82_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "151", "SubInstance" : "grp_dense_relu_fu_530", "Port" : "w_local_82_1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "w_local_82_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "151", "SubInstance" : "grp_dense_relu_fu_530", "Port" : "w_local_82_2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "w_local_82_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "151", "SubInstance" : "grp_dense_relu_fu_530", "Port" : "w_local_82_3", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "f_x_lsb_table", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "167", "SubInstance" : "grp_exp_12_3_s_fu_594", "Port" : "f_x_lsb_table", "Inst_start_state" : "12", "Inst_end_state" : "18"}]},
			{"Name" : "exp_x_msb_2_m_1_table", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "167", "SubInstance" : "grp_exp_12_3_s_fu_594", "Port" : "exp_x_msb_2_m_1_table", "Inst_start_state" : "12", "Inst_end_state" : "18"}]},
			{"Name" : "exp_x_msb_1_table", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "167", "SubInstance" : "grp_exp_12_3_s_fu_594", "Port" : "exp_x_msb_1_table", "Inst_start_state" : "12", "Inst_end_state" : "18"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv1_out_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv1_out_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_1_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_2_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_3_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_4_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_5_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_6_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_7_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_8_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_9_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_out_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_out_1_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_out_2_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_out_3_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406", "Parent" : "0", "Child" : ["18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33"],
		"CDFG" : "conv1d_relu",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40000", "EstimateLatencyMax" : "40000",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "INPUT_r", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "INPUT_r_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "INPUT_r_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "input_r_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "w_local_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_6", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "CONV1_F_CONV1_X", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "7", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_0_U", "Parent" : "17"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_1_U", "Parent" : "17"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_2_U", "Parent" : "17"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_3_U", "Parent" : "17"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_4_U", "Parent" : "17"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_5_U", "Parent" : "17"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.w_local_6_U", "Parent" : "17"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.sparsemux_17_3_9_1_1_U1", "Parent" : "17"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_11s_18s_21_4_1_U2", "Parent" : "17"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_10s_21ns_21_4_1_U3", "Parent" : "17"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_10s_21ns_21_4_1_U4", "Parent" : "17"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_10s_21ns_21_4_1_U5", "Parent" : "17"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_9s_21ns_21_4_1_U6", "Parent" : "17"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_10s_21ns_21_4_1_U7", "Parent" : "17"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.mac_muladd_12s_11s_21ns_21_4_1_U8", "Parent" : "17"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu_fu_406.flow_control_loop_pipe_sequential_init_U", "Parent" : "17"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_maxpool_fu_432", "Parent" : "0", "Child" : ["35", "36", "37"],
		"CDFG" : "maxpool",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2871", "EstimateLatencyMax" : "2871",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_0_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_0_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_0_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_0_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_0_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1_4", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "POOL_F_POOL_X", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter14", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter14", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_maxpool_fu_432.urem_9ns_4ns_3_13_1_U25", "Parent" : "34"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_maxpool_fu_432.mul_9ns_11ns_19_1_1_U26", "Parent" : "34"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_maxpool_fu_432.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448", "Parent" : "0", "Child" : ["39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146"],
		"CDFG" : "conv1d_relu2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "11354", "EstimateLatencyMax" : "11354",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_0_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_0_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_0_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_0_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "output_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "w_local_80_0_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_0_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_0_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_0_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_0_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_1_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_1_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_1_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_1_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_1_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_2_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_2_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_2_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_2_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_3_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_3_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_3_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_3_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_80_3_4", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "CONV2_F_CONV2_X", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter29", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter29", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_0_0_U", "Parent" : "38"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_0_1_U", "Parent" : "38"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_0_2_U", "Parent" : "38"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_0_3_U", "Parent" : "38"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_0_4_U", "Parent" : "38"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_1_0_U", "Parent" : "38"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_1_1_U", "Parent" : "38"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_1_2_U", "Parent" : "38"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_1_3_U", "Parent" : "38"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_1_4_U", "Parent" : "38"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_2_0_U", "Parent" : "38"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_2_1_U", "Parent" : "38"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_2_2_U", "Parent" : "38"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_2_3_U", "Parent" : "38"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_2_4_U", "Parent" : "38"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_3_0_U", "Parent" : "38"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_3_1_U", "Parent" : "38"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_3_2_U", "Parent" : "38"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_3_3_U", "Parent" : "38"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.w_local_80_3_4_U", "Parent" : "38"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mul_9ns_11ns_19_1_1_U41", "Parent" : "38"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.urem_9ns_4ns_3_13_1_U42", "Parent" : "38"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mul_9ns_11ns_19_1_1_U43", "Parent" : "38"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mul_9ns_11ns_19_1_1_U44", "Parent" : "38"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mul_9ns_11ns_19_1_1_U45", "Parent" : "38"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mul_9ns_11ns_19_1_1_U46", "Parent" : "38"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U47", "Parent" : "38"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U48", "Parent" : "38"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U49", "Parent" : "38"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U50", "Parent" : "38"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U51", "Parent" : "38"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U52", "Parent" : "38"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U53", "Parent" : "38"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U54", "Parent" : "38"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U55", "Parent" : "38"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U56", "Parent" : "38"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U57", "Parent" : "38"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U58", "Parent" : "38"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U59", "Parent" : "38"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U60", "Parent" : "38"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U61", "Parent" : "38"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U62", "Parent" : "38"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U63", "Parent" : "38"},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U64", "Parent" : "38"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U65", "Parent" : "38"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U66", "Parent" : "38"},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U67", "Parent" : "38"},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U68", "Parent" : "38"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U69", "Parent" : "38"},
	{"ID" : "88", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U70", "Parent" : "38"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U71", "Parent" : "38"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U72", "Parent" : "38"},
	{"ID" : "91", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U73", "Parent" : "38"},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U74", "Parent" : "38"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U75", "Parent" : "38"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U76", "Parent" : "38"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U77", "Parent" : "38"},
	{"ID" : "96", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U78", "Parent" : "38"},
	{"ID" : "97", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U79", "Parent" : "38"},
	{"ID" : "98", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U80", "Parent" : "38"},
	{"ID" : "99", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U81", "Parent" : "38"},
	{"ID" : "100", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U82", "Parent" : "38"},
	{"ID" : "101", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U83", "Parent" : "38"},
	{"ID" : "102", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U84", "Parent" : "38"},
	{"ID" : "103", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U85", "Parent" : "38"},
	{"ID" : "104", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_11_3_11_1_1_U86", "Parent" : "38"},
	{"ID" : "105", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.sparsemux_33_4_10_1_1_U87", "Parent" : "38"},
	{"ID" : "106", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_19s_21_4_1_U88", "Parent" : "38"},
	{"ID" : "107", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U89", "Parent" : "38"},
	{"ID" : "108", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U90", "Parent" : "38"},
	{"ID" : "109", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U91", "Parent" : "38"},
	{"ID" : "110", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U92", "Parent" : "38"},
	{"ID" : "111", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U93", "Parent" : "38"},
	{"ID" : "112", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U94", "Parent" : "38"},
	{"ID" : "113", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U95", "Parent" : "38"},
	{"ID" : "114", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U96", "Parent" : "38"},
	{"ID" : "115", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U97", "Parent" : "38"},
	{"ID" : "116", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U98", "Parent" : "38"},
	{"ID" : "117", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U99", "Parent" : "38"},
	{"ID" : "118", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U100", "Parent" : "38"},
	{"ID" : "119", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U101", "Parent" : "38"},
	{"ID" : "120", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U102", "Parent" : "38"},
	{"ID" : "121", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U103", "Parent" : "38"},
	{"ID" : "122", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U104", "Parent" : "38"},
	{"ID" : "123", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U105", "Parent" : "38"},
	{"ID" : "124", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U106", "Parent" : "38"},
	{"ID" : "125", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U107", "Parent" : "38"},
	{"ID" : "126", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U108", "Parent" : "38"},
	{"ID" : "127", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U109", "Parent" : "38"},
	{"ID" : "128", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U110", "Parent" : "38"},
	{"ID" : "129", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U111", "Parent" : "38"},
	{"ID" : "130", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U112", "Parent" : "38"},
	{"ID" : "131", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U113", "Parent" : "38"},
	{"ID" : "132", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U114", "Parent" : "38"},
	{"ID" : "133", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U115", "Parent" : "38"},
	{"ID" : "134", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U116", "Parent" : "38"},
	{"ID" : "135", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_12s_11ns_21ns_21_4_1_U117", "Parent" : "38"},
	{"ID" : "136", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U118", "Parent" : "38"},
	{"ID" : "137", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U119", "Parent" : "38"},
	{"ID" : "138", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U120", "Parent" : "38"},
	{"ID" : "139", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U121", "Parent" : "38"},
	{"ID" : "140", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U122", "Parent" : "38"},
	{"ID" : "141", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U123", "Parent" : "38"},
	{"ID" : "142", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U124", "Parent" : "38"},
	{"ID" : "143", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U125", "Parent" : "38"},
	{"ID" : "144", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_10s_21ns_21_4_1_U126", "Parent" : "38"},
	{"ID" : "145", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.mac_muladd_11ns_11s_21ns_21_4_1_U127", "Parent" : "38"},
	{"ID" : "146", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_conv1d_relu2_fu_448.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "147", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_gap_fu_506", "Parent" : "0", "Child" : ["148"],
		"CDFG" : "gap",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5745", "EstimateLatencyMax" : "5745",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "148", "SubInstance" : "grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226", "Port" : "input_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "148", "SubInstance" : "grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226", "Port" : "input_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "148", "SubInstance" : "grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226", "Port" : "input_2", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "input_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "148", "SubInstance" : "grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226", "Port" : "input_3", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "output_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_9", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_10", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_11", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_12", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_13", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_14", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_15", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "GAP_F", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "148", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_gap_fu_506.grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226", "Parent" : "147", "Child" : ["149", "150"],
		"CDFG" : "gap_Pipeline_VITIS_LOOP_115_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "356", "EstimateLatencyMax" : "356",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lshr_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "sum_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_115_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "149", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_gap_fu_506.grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226.sparsemux_9_2_11_1_1_U172", "Parent" : "148"},
	{"ID" : "150", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_gap_fu_506.grp_gap_Pipeline_VITIS_LOOP_115_1_fu_226.flow_control_loop_pipe_sequential_init_U", "Parent" : "148"},
	{"ID" : "151", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530", "Parent" : "0", "Child" : ["152", "161"],
		"CDFG" : "dense_relu",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "625", "EstimateLatencyMax" : "625",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_9", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_10", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_11", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_12", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_13", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_14", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_15", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_local_82_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "152", "SubInstance" : "grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380", "Port" : "w_local_82_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w_local_82_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "152", "SubInstance" : "grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380", "Port" : "w_local_82_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w_local_82_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "152", "SubInstance" : "grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380", "Port" : "w_local_82_2", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "w_local_82_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "152", "SubInstance" : "grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380", "Port" : "w_local_82_3", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}],
		"Loop" : [
			{"Name" : "D1_U", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "152", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380", "Parent" : "151", "Child" : ["153", "154", "155", "156", "157", "158", "159", "160"],
		"CDFG" : "dense_relu_Pipeline_VITIS_LOOP_146_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "36", "EstimateLatencyMax" : "36",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sext_ln145", "Type" : "None", "Direction" : "I"},
			{"Name" : "u", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_15_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "phi_ln148_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "w_local_82_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_82_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_82_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "w_local_82_3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_146_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "153", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.w_local_82_0_U", "Parent" : "152"},
	{"ID" : "154", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.w_local_82_1_U", "Parent" : "152"},
	{"ID" : "155", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.w_local_82_2_U", "Parent" : "152"},
	{"ID" : "156", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.w_local_82_3_U", "Parent" : "152"},
	{"ID" : "157", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.sparsemux_33_4_12_1_1_U201", "Parent" : "152"},
	{"ID" : "158", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.sparsemux_9_2_12_1_1_U202", "Parent" : "152"},
	{"ID" : "159", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.mac_muladd_12s_12s_21ns_21_4_1_U203", "Parent" : "152"},
	{"ID" : "160", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.grp_dense_relu_Pipeline_VITIS_LOOP_146_2_fu_380.flow_control_loop_pipe_sequential_init_U", "Parent" : "152"},
	{"ID" : "161", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_relu_fu_530.sparsemux_33_4_8_1_1_U230", "Parent" : "151"},
	{"ID" : "162", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dense_linear_fu_574", "Parent" : "0", "Child" : ["163", "164", "165", "166"],
		"CDFG" : "dense_linear",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "35", "EstimateLatencyMax" : "35",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_0_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_1_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_2_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_3_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_4_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_5_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_6_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_7_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_8_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_9_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_10_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_11_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_12_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_13_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_14_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_15_val", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_177_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "163", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_linear_fu_574.sparsemux_33_4_11_1_1_U264", "Parent" : "162"},
	{"ID" : "164", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_linear_fu_574.sparsemux_33_4_12_1_1_x_U265", "Parent" : "162"},
	{"ID" : "165", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_linear_fu_574.mac_muladd_12s_11ns_21ns_21_4_1_U266", "Parent" : "162"},
	{"ID" : "166", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dense_linear_fu_574.flow_control_loop_pipe_sequential_init_U", "Parent" : "162"},
	{"ID" : "167", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594", "Parent" : "0", "Child" : ["168", "169", "170", "171", "172"],
		"CDFG" : "exp_12_3_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "5", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "1",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"},
			{"Name" : "f_x_lsb_table", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "exp_x_msb_2_m_1_table", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "exp_x_msb_1_table", "Type" : "Memory", "Direction" : "I"}]},
	{"ID" : "168", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594.f_x_lsb_table_U", "Parent" : "167"},
	{"ID" : "169", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594.exp_x_msb_2_m_1_table_U", "Parent" : "167"},
	{"ID" : "170", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594.exp_x_msb_1_table_U", "Parent" : "167"},
	{"ID" : "171", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594.mul_25ns_25ns_50_1_0_U285", "Parent" : "167"},
	{"ID" : "172", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_exp_12_3_s_fu_594.mul_25ns_18ns_43_1_0_U286", "Parent" : "167"},
	{"ID" : "173", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "174", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.INPUT_r_m_axi_U", "Parent" : "0"},
	{"ID" : "175", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.OUTPUT_r_m_axi_U", "Parent" : "0"},
	{"ID" : "176", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sdiv_20ns_13s_20_24_seq_1_U293", "Parent" : "0"}]}
