// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_dense_relu (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        output_0,
        output_0_ap_vld,
        output_1,
        output_1_ap_vld,
        output_2,
        output_2_ap_vld,
        output_3,
        output_3_ap_vld,
        output_4,
        output_4_ap_vld,
        output_5,
        output_5_ap_vld,
        output_6,
        output_6_ap_vld,
        output_7,
        output_7_ap_vld,
        output_8,
        output_8_ap_vld,
        output_9,
        output_9_ap_vld,
        output_10,
        output_10_ap_vld,
        output_11,
        output_11_ap_vld,
        output_12,
        output_12_ap_vld,
        output_13,
        output_13_ap_vld,
        output_14,
        output_14_ap_vld,
        output_15,
        output_15_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] input_0_val;
input  [11:0] input_1_val;
input  [11:0] input_2_val;
input  [11:0] input_3_val;
input  [11:0] input_4_val;
input  [11:0] input_5_val;
input  [11:0] input_6_val;
input  [11:0] input_7_val;
input  [11:0] input_8_val;
input  [11:0] input_9_val;
input  [11:0] input_10_val;
input  [11:0] input_11_val;
input  [11:0] input_12_val;
input  [11:0] input_13_val;
input  [11:0] input_14_val;
input  [11:0] input_15_val;
output  [10:0] output_0;
output   output_0_ap_vld;
output  [10:0] output_1;
output   output_1_ap_vld;
output  [10:0] output_2;
output   output_2_ap_vld;
output  [10:0] output_3;
output   output_3_ap_vld;
output  [10:0] output_4;
output   output_4_ap_vld;
output  [10:0] output_5;
output   output_5_ap_vld;
output  [10:0] output_6;
output   output_6_ap_vld;
output  [10:0] output_7;
output   output_7_ap_vld;
output  [10:0] output_8;
output   output_8_ap_vld;
output  [10:0] output_9;
output   output_9_ap_vld;
output  [10:0] output_10;
output   output_10_ap_vld;
output  [10:0] output_11;
output   output_11_ap_vld;
output  [10:0] output_12;
output   output_12_ap_vld;
output  [10:0] output_13;
output   output_13_ap_vld;
output  [10:0] output_14;
output   output_14_ap_vld;
output  [10:0] output_15;
output   output_15_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_0_ap_vld;
reg output_1_ap_vld;
reg output_2_ap_vld;
reg output_3_ap_vld;
reg output_4_ap_vld;
reg output_5_ap_vld;
reg output_6_ap_vld;
reg output_7_ap_vld;
reg output_8_ap_vld;
reg output_9_ap_vld;
reg output_10_ap_vld;
reg output_11_ap_vld;
reg output_12_ap_vld;
reg output_13_ap_vld;
reg output_14_ap_vld;
reg output_15_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] add_ln146_fu_425_p2;
reg   [4:0] add_ln146_reg_679;
wire    ap_CS_fsm_state2;
wire   [3:0] trunc_ln146_fu_431_p1;
reg   [3:0] trunc_ln146_reg_684;
wire   [7:0] acc_fu_436_p35;
reg   [7:0] acc_reg_690;
wire    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start;
wire    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_done;
wire    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_idle;
wire    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_ready;
wire   [11:0] grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out;
wire    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out_ap_vld;
reg    grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg;
wire   [0:0] icmp_ln146_fu_419_p2;
wire    ap_CS_fsm_state3;
reg   [4:0] u_fu_164;
wire    ap_CS_fsm_state4;
wire   [10:0] select_ln152_fu_522_p3;
wire   [7:0] acc_fu_436_p33;
wire   [3:0] acc_fu_436_p34;
wire   [0:0] icmp_ln152_fu_516_p2;
wire   [10:0] trunc_ln148_fu_512_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire   [3:0] acc_fu_436_p1;
wire   [3:0] acc_fu_436_p3;
wire   [3:0] acc_fu_436_p5;
wire   [3:0] acc_fu_436_p7;
wire   [3:0] acc_fu_436_p9;
wire   [3:0] acc_fu_436_p11;
wire   [3:0] acc_fu_436_p13;
wire   [3:0] acc_fu_436_p15;
wire  signed [3:0] acc_fu_436_p17;
wire  signed [3:0] acc_fu_436_p19;
wire  signed [3:0] acc_fu_436_p21;
wire  signed [3:0] acc_fu_436_p23;
wire  signed [3:0] acc_fu_436_p25;
wire  signed [3:0] acc_fu_436_p27;
wire  signed [3:0] acc_fu_436_p29;
wire  signed [3:0] acc_fu_436_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg = 1'b0;
#0 u_fu_164 = 5'd0;
end

ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2 grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start),
    .ap_done(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_done),
    .ap_idle(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_idle),
    .ap_ready(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_ready),
    .sext_ln147(acc_reg_690),
    .u(trunc_ln146_reg_684),
    .input_0_val(input_0_val),
    .input_1_val(input_1_val),
    .input_2_val(input_2_val),
    .input_3_val(input_3_val),
    .input_4_val(input_4_val),
    .input_5_val(input_5_val),
    .input_6_val(input_6_val),
    .input_7_val(input_7_val),
    .input_8_val(input_8_val),
    .input_9_val(input_9_val),
    .input_10_val(input_10_val),
    .input_11_val(input_11_val),
    .input_12_val(input_12_val),
    .input_13_val(input_13_val),
    .input_14_val(input_14_val),
    .input_15_val(input_15_val),
    .phi_ln150_out(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out),
    .phi_ln150_out_ap_vld(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out_ap_vld)
);

(* dissolve_hierarchy = "yes" *) ecg_cnn_sparsemux_33_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 8 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 8 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 8 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 8 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 8 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 8 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 8 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_33_4_8_1_1_U230(
    .din0(8'd0),
    .din1(8'd107),
    .din2(8'd54),
    .din3(8'd230),
    .din4(8'd82),
    .din5(8'd244),
    .din6(8'd246),
    .din7(8'd236),
    .din8(8'd81),
    .din9(8'd8),
    .din10(8'd87),
    .din11(8'd74),
    .din12(8'd236),
    .din13(8'd81),
    .din14(8'd38),
    .din15(8'd216),
    .def(acc_fu_436_p33),
    .sel(acc_fu_436_p34),
    .dout(acc_fu_436_p35)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln146_fu_419_p2 == 1'd0))) begin
            grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_ready == 1'b1)) begin
            grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        u_fu_164 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        u_fu_164 <= add_ln146_reg_679;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        acc_reg_690 <= acc_fu_436_p35;
        add_ln146_reg_679 <= add_ln146_fu_425_p2;
        trunc_ln146_reg_684 <= trunc_ln146_fu_431_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln146_fu_419_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln146_fu_419_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd0))) begin
        output_0_ap_vld = 1'b1;
    end else begin
        output_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd10))) begin
        output_10_ap_vld = 1'b1;
    end else begin
        output_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd11))) begin
        output_11_ap_vld = 1'b1;
    end else begin
        output_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd12))) begin
        output_12_ap_vld = 1'b1;
    end else begin
        output_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd13))) begin
        output_13_ap_vld = 1'b1;
    end else begin
        output_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd14))) begin
        output_14_ap_vld = 1'b1;
    end else begin
        output_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd15))) begin
        output_15_ap_vld = 1'b1;
    end else begin
        output_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd1))) begin
        output_1_ap_vld = 1'b1;
    end else begin
        output_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd2))) begin
        output_2_ap_vld = 1'b1;
    end else begin
        output_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd3))) begin
        output_3_ap_vld = 1'b1;
    end else begin
        output_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd4))) begin
        output_4_ap_vld = 1'b1;
    end else begin
        output_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd5))) begin
        output_5_ap_vld = 1'b1;
    end else begin
        output_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd6))) begin
        output_6_ap_vld = 1'b1;
    end else begin
        output_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd7))) begin
        output_7_ap_vld = 1'b1;
    end else begin
        output_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd8))) begin
        output_8_ap_vld = 1'b1;
    end else begin
        output_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (trunc_ln146_reg_684 == 4'd9))) begin
        output_9_ap_vld = 1'b1;
    end else begin
        output_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln146_fu_419_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_436_p33 = 'bx;

assign acc_fu_436_p34 = u_fu_164[3:0];

assign add_ln146_fu_425_p2 = (u_fu_164 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start = grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_ap_start_reg;

assign icmp_ln146_fu_419_p2 = ((u_fu_164 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_516_p2 = (($signed(grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign output_0 = select_ln152_fu_522_p3;

assign output_1 = select_ln152_fu_522_p3;

assign output_10 = select_ln152_fu_522_p3;

assign output_11 = select_ln152_fu_522_p3;

assign output_12 = select_ln152_fu_522_p3;

assign output_13 = select_ln152_fu_522_p3;

assign output_14 = select_ln152_fu_522_p3;

assign output_15 = select_ln152_fu_522_p3;

assign output_2 = select_ln152_fu_522_p3;

assign output_3 = select_ln152_fu_522_p3;

assign output_4 = select_ln152_fu_522_p3;

assign output_5 = select_ln152_fu_522_p3;

assign output_6 = select_ln152_fu_522_p3;

assign output_7 = select_ln152_fu_522_p3;

assign output_8 = select_ln152_fu_522_p3;

assign output_9 = select_ln152_fu_522_p3;

assign select_ln152_fu_522_p3 = ((icmp_ln152_fu_516_p2[0:0] == 1'b1) ? trunc_ln148_fu_512_p1 : 11'd0);

assign trunc_ln146_fu_431_p1 = u_fu_164[3:0];

assign trunc_ln148_fu_512_p1 = grp_dense_relu_Pipeline_VITIS_LOOP_148_2_fu_380_phi_ln150_out[10:0];

endmodule //ecg_cnn_dense_relu
