// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln147,
        u,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        phi_ln150_out,
        phi_ln150_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] sext_ln147;
input  [3:0] u;
input  [11:0] input_0_val;
input  [11:0] input_1_val;
input  [11:0] input_2_val;
input  [11:0] input_3_val;
input  [11:0] input_4_val;
input  [11:0] input_5_val;
input  [11:0] input_6_val;
input  [11:0] input_7_val;
input  [11:0] input_8_val;
input  [11:0] input_9_val;
input  [11:0] input_10_val;
input  [11:0] input_11_val;
input  [11:0] input_12_val;
input  [11:0] input_13_val;
input  [11:0] input_14_val;
input  [11:0] input_15_val;
output  [11:0] phi_ln150_out;
output   phi_ln150_out_ap_vld;

reg ap_idle;
reg phi_ln150_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln148_reg_566;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] w_local_82_0_address0;
wire   [11:0] w_local_82_0_q0;
wire   [5:0] w_local_82_1_address0;
wire   [11:0] w_local_82_1_q0;
wire   [5:0] w_local_82_2_address0;
wire   [11:0] w_local_82_2_q0;
wire   [5:0] w_local_82_3_address0;
wire   [10:0] w_local_82_3_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln148_fu_345_p2;
wire   [1:0] trunc_ln148_1_fu_361_p1;
reg   [1:0] trunc_ln148_1_reg_570;
wire   [11:0] tmp_fu_391_p35;
reg  signed [11:0] tmp_reg_595;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln150_fu_383_p1;
wire    ap_block_pp0_stage0;
reg   [11:0] phi_ln150_fu_144;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [11:0] acc_fu_148;
wire  signed [11:0] sext_ln147_cast_fu_323_p1;
wire    ap_block_pp0_stage1;
reg   [4:0] i_fu_152;
wire   [4:0] add_ln148_fu_351_p2;
reg   [4:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0_01001;
reg    w_local_82_0_ce0_local;
reg    w_local_82_1_ce0_local;
reg    w_local_82_2_ce0_local;
reg    w_local_82_3_ce0_local;
wire   [1:0] lshr_ln_fu_365_p4;
wire   [5:0] tmp_1_fu_375_p3;
wire   [11:0] tmp_fu_391_p33;
wire   [3:0] tmp_fu_391_p34;
wire  signed [11:0] tmp_s_fu_475_p8;
wire   [11:0] tmp_s_fu_475_p9;
wire  signed [11:0] tmp_s_fu_475_p11;
wire  signed [20:0] acc_1_fu_513_p1;
wire   [20:0] grp_fu_536_p3;
wire   [20:0] grp_fu_536_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_fu_391_p1;
wire   [3:0] tmp_fu_391_p3;
wire   [3:0] tmp_fu_391_p5;
wire   [3:0] tmp_fu_391_p7;
wire   [3:0] tmp_fu_391_p9;
wire   [3:0] tmp_fu_391_p11;
wire   [3:0] tmp_fu_391_p13;
wire   [3:0] tmp_fu_391_p15;
wire  signed [3:0] tmp_fu_391_p17;
wire  signed [3:0] tmp_fu_391_p19;
wire  signed [3:0] tmp_fu_391_p21;
wire  signed [3:0] tmp_fu_391_p23;
wire  signed [3:0] tmp_fu_391_p25;
wire  signed [3:0] tmp_fu_391_p27;
wire  signed [3:0] tmp_fu_391_p29;
wire  signed [3:0] tmp_fu_391_p31;
wire   [1:0] tmp_s_fu_475_p1;
wire   [1:0] tmp_s_fu_475_p3;
wire  signed [1:0] tmp_s_fu_475_p5;
wire  signed [1:0] tmp_s_fu_475_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 phi_ln150_fu_144 = 12'd0;
#0 acc_fu_148 = 12'd0;
#0 i_fu_152 = 5'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_0_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w_local_82_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_local_82_0_address0),
    .ce0(w_local_82_0_ce0_local),
    .q0(w_local_82_0_q0)
);

ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_1_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w_local_82_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_local_82_1_address0),
    .ce0(w_local_82_1_ce0_local),
    .q0(w_local_82_1_q0)
);

ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_2_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w_local_82_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_local_82_2_address0),
    .ce0(w_local_82_2_ce0_local),
    .q0(w_local_82_2_q0)
);

ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2_w_local_82_3_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w_local_82_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_local_82_3_address0),
    .ce0(w_local_82_3_ce0_local),
    .q0(w_local_82_3_q0)
);

(* dissolve_hierarchy = "yes" *) ecg_cnn_sparsemux_33_4_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
sparsemux_33_4_12_1_1_U201(
    .din0(input_0_val),
    .din1(input_1_val),
    .din2(input_2_val),
    .din3(input_3_val),
    .din4(input_4_val),
    .din5(input_5_val),
    .din6(input_6_val),
    .din7(input_7_val),
    .din8(input_8_val),
    .din9(input_9_val),
    .din10(input_10_val),
    .din11(input_11_val),
    .din12(input_12_val),
    .din13(input_13_val),
    .din14(input_14_val),
    .din15(input_15_val),
    .def(tmp_fu_391_p33),
    .sel(tmp_fu_391_p34),
    .dout(tmp_fu_391_p35)
);

(* dissolve_hierarchy = "yes" *) ecg_cnn_sparsemux_9_2_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 12 ))
sparsemux_9_2_12_1_1_U202(
    .din0(w_local_82_0_q0),
    .din1(w_local_82_1_q0),
    .din2(w_local_82_2_q0),
    .din3(tmp_s_fu_475_p8),
    .def(tmp_s_fu_475_p9),
    .sel(trunc_ln148_1_reg_570),
    .dout(tmp_s_fu_475_p11)
);

ecg_cnn_mac_muladd_12s_12s_21ns_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
mac_muladd_12s_12s_21ns_21_4_1_U203(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_fu_475_p11),
    .din1(tmp_reg_595),
    .din2(grp_fu_536_p2),
    .ce(1'b1),
    .dout(grp_fu_536_p3)
);

ecg_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_fu_148 <= sext_ln147_cast_fu_323_p1;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            acc_fu_148 <= {{acc_1_fu_513_p1[20:9]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln148_fu_345_p2 == 1'd0))) begin
            i_fu_152 <= add_ln148_fu_351_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_152 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_ln150_fu_144 <= 12'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            phi_ln150_fu_144 <= {{acc_1_fu_513_p1[20:9]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln148_reg_566 <= icmp_ln148_fu_345_p2;
        tmp_reg_595 <= tmp_fu_391_p35;
        trunc_ln148_1_reg_570 <= trunc_ln148_1_fu_361_p1;
    end
end

always @ (*) begin
    if (((icmp_ln148_reg_566 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln148_reg_566 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_152;
    end
end

always @ (*) begin
    if (((icmp_ln148_reg_566 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        phi_ln150_out_ap_vld = 1'b1;
    end else begin
        phi_ln150_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_local_82_0_ce0_local = 1'b1;
    end else begin
        w_local_82_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_local_82_1_ce0_local = 1'b1;
    end else begin
        w_local_82_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_local_82_2_ce0_local = 1'b1;
    end else begin
        w_local_82_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_local_82_3_ce0_local = 1'b1;
    end else begin
        w_local_82_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_513_p1 = grp_fu_536_p3;

assign add_ln148_fu_351_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign grp_fu_536_p2 = {{acc_fu_148}, {9'd0}};

assign icmp_ln148_fu_345_p2 = ((ap_sig_allocacmp_i_2 == 5'd16) ? 1'b1 : 1'b0);

assign lshr_ln_fu_365_p4 = {{ap_sig_allocacmp_i_2[3:2]}};

assign phi_ln150_out = phi_ln150_fu_144;

assign sext_ln147_cast_fu_323_p1 = $signed(sext_ln147);

assign tmp_1_fu_375_p3 = {{u}, {lshr_ln_fu_365_p4}};

assign tmp_fu_391_p33 = 'bx;

assign tmp_fu_391_p34 = ap_sig_allocacmp_i_2[3:0];

assign tmp_s_fu_475_p8 = $signed(w_local_82_3_q0);

assign tmp_s_fu_475_p9 = 'bx;

assign trunc_ln148_1_fu_361_p1 = ap_sig_allocacmp_i_2[1:0];

assign w_local_82_0_address0 = zext_ln150_fu_383_p1;

assign w_local_82_1_address0 = zext_ln150_fu_383_p1;

assign w_local_82_2_address0 = zext_ln150_fu_383_p1;

assign w_local_82_3_address0 = zext_ln150_fu_383_p1;

assign zext_ln150_fu_383_p1 = tmp_1_fu_375_p3;

endmodule //ecg_cnn_dense_relu_Pipeline_VITIS_LOOP_148_2
