// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_gap (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        output_0,
        output_0_ap_vld,
        output_1,
        output_1_ap_vld,
        output_2,
        output_2_ap_vld,
        output_3,
        output_3_ap_vld,
        output_4,
        output_4_ap_vld,
        output_5,
        output_5_ap_vld,
        output_6,
        output_6_ap_vld,
        output_7,
        output_7_ap_vld,
        output_8,
        output_8_ap_vld,
        output_9,
        output_9_ap_vld,
        output_10,
        output_10_ap_vld,
        output_11,
        output_11_ap_vld,
        output_12,
        output_12_ap_vld,
        output_13,
        output_13_ap_vld,
        output_14,
        output_14_ap_vld,
        output_15,
        output_15_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] input_0_address0;
output   input_0_ce0;
input  [10:0] input_0_q0;
output  [10:0] input_1_address0;
output   input_1_ce0;
input  [10:0] input_1_q0;
output  [10:0] input_2_address0;
output   input_2_ce0;
input  [10:0] input_2_q0;
output  [10:0] input_3_address0;
output   input_3_ce0;
input  [10:0] input_3_q0;
output  [11:0] output_0;
output   output_0_ap_vld;
output  [11:0] output_1;
output   output_1_ap_vld;
output  [11:0] output_2;
output   output_2_ap_vld;
output  [11:0] output_3;
output   output_3_ap_vld;
output  [11:0] output_4;
output   output_4_ap_vld;
output  [11:0] output_5;
output   output_5_ap_vld;
output  [11:0] output_6;
output   output_6_ap_vld;
output  [11:0] output_7;
output   output_7_ap_vld;
output  [11:0] output_8;
output   output_8_ap_vld;
output  [11:0] output_9;
output   output_9_ap_vld;
output  [11:0] output_10;
output   output_10_ap_vld;
output  [11:0] output_11;
output   output_11_ap_vld;
output  [11:0] output_12;
output   output_12_ap_vld;
output  [11:0] output_13;
output   output_13_ap_vld;
output  [11:0] output_14;
output   output_14_ap_vld;
output  [11:0] output_15;
output   output_15_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_0_ap_vld;
reg output_1_ap_vld;
reg output_2_ap_vld;
reg output_3_ap_vld;
reg output_4_ap_vld;
reg output_5_ap_vld;
reg output_6_ap_vld;
reg output_7_ap_vld;
reg output_8_ap_vld;
reg output_9_ap_vld;
reg output_10_ap_vld;
reg output_11_ap_vld;
reg output_12_ap_vld;
reg output_13_ap_vld;
reg output_14_ap_vld;
reg output_15_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] add_ln115_fu_255_p2;
reg   [4:0] add_ln115_reg_353;
wire    ap_CS_fsm_state2;
wire   [3:0] trunc_ln115_fu_261_p1;
reg   [3:0] trunc_ln115_reg_358;
wire   [1:0] trunc_ln115_1_fu_265_p1;
reg   [1:0] trunc_ln115_1_reg_363;
reg   [1:0] lshr_ln_reg_368;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_idle;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready;
wire   [10:0] grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0;
wire   [10:0] grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0;
wire   [10:0] grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0;
wire   [10:0] grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0;
wire   [11:0] grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;
wire    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out_ap_vld;
reg    grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg;
wire   [0:0] icmp_ln115_fu_249_p2;
wire    ap_CS_fsm_state3;
reg   [4:0] f_fu_106;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg = 1'b0;
#0 f_fu_106 = 5'd0;
end

ecg_cnn_gap_Pipeline_VITIS_LOOP_117_1 grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start),
    .ap_done(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done),
    .ap_idle(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_idle),
    .ap_ready(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready),
    .lshr_ln(lshr_ln_reg_368),
    .input_0_address0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0),
    .input_0_ce0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0),
    .input_0_q0(input_0_q0),
    .input_1_address0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0),
    .input_1_ce0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0),
    .input_1_q0(input_1_q0),
    .input_2_address0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0),
    .input_2_ce0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0),
    .input_2_q0(input_2_q0),
    .input_3_address0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0),
    .input_3_ce0(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0),
    .input_3_q0(input_3_q0),
    .empty(trunc_ln115_1_reg_363),
    .sum_out(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out),
    .sum_out_ap_vld(grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln115_fu_249_p2 == 1'd0))) begin
            grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= 1'b1;
        end else if ((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_ready == 1'b1)) begin
            grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        f_fu_106 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        f_fu_106 <= add_ln115_reg_353;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln115_reg_353 <= add_ln115_fu_255_p2;
        lshr_ln_reg_368 <= {{f_fu_106[3:2]}};
        trunc_ln115_1_reg_363 <= trunc_ln115_1_fu_265_p1;
        trunc_ln115_reg_358 <= trunc_ln115_fu_261_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln115_fu_249_p2 == 1'd1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln115_fu_249_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        output_0_ap_vld = 1'b1;
    end else begin
        output_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd10) & (1'b1 == ap_CS_fsm_state4))) begin
        output_10_ap_vld = 1'b1;
    end else begin
        output_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd11) & (1'b1 == ap_CS_fsm_state4))) begin
        output_11_ap_vld = 1'b1;
    end else begin
        output_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd12) & (1'b1 == ap_CS_fsm_state4))) begin
        output_12_ap_vld = 1'b1;
    end else begin
        output_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd13) & (1'b1 == ap_CS_fsm_state4))) begin
        output_13_ap_vld = 1'b1;
    end else begin
        output_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd14) & (1'b1 == ap_CS_fsm_state4))) begin
        output_14_ap_vld = 1'b1;
    end else begin
        output_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd15) & (1'b1 == ap_CS_fsm_state4))) begin
        output_15_ap_vld = 1'b1;
    end else begin
        output_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_1_ap_vld = 1'b1;
    end else begin
        output_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        output_2_ap_vld = 1'b1;
    end else begin
        output_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        output_3_ap_vld = 1'b1;
    end else begin
        output_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        output_4_ap_vld = 1'b1;
    end else begin
        output_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        output_5_ap_vld = 1'b1;
    end else begin
        output_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        output_6_ap_vld = 1'b1;
    end else begin
        output_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd7) & (1'b1 == ap_CS_fsm_state4))) begin
        output_7_ap_vld = 1'b1;
    end else begin
        output_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd8) & (1'b1 == ap_CS_fsm_state4))) begin
        output_8_ap_vld = 1'b1;
    end else begin
        output_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln115_reg_358 == 4'd9) & (1'b1 == ap_CS_fsm_state4))) begin
        output_9_ap_vld = 1'b1;
    end else begin
        output_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln115_fu_249_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_fu_255_p2 = (f_fu_106 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_ap_start_reg;

assign icmp_ln115_fu_249_p2 = ((f_fu_106 == 5'd16) ? 1'b1 : 1'b0);

assign input_0_address0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_address0;

assign input_0_ce0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_0_ce0;

assign input_1_address0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_address0;

assign input_1_ce0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_1_ce0;

assign input_2_address0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_address0;

assign input_2_ce0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_2_ce0;

assign input_3_address0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_address0;

assign input_3_ce0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_input_3_ce0;

assign output_0 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_1 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_10 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_11 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_12 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_13 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_14 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_15 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_2 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_3 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_4 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_5 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_6 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_7 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_8 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign output_9 = grp_gap_Pipeline_VITIS_LOOP_117_1_fu_226_sum_out;

assign trunc_ln115_1_fu_265_p1 = f_fu_106[1:0];

assign trunc_ln115_fu_261_p1 = f_fu_106[3:0];

endmodule //ecg_cnn_gap
